$axure.loadCurrentPage({
  "url":"file.html",
  "generationDate":new Date(1415447467688.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a90932f17f840a297eb0248988ddc9b",
    "type":"Axure:Page",
    "name":"File",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ba61229ceb4c4f2d869715dcebe98d20",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"4f5df35342ce47e0a30716c2b1172162"},
{
          "id":"caa126b49f474f35a64fd8e9630fab14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":190},
            "size":{
              "width":298,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bc87a5b10c746739bb7cb9508753026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":190},
                "size":{
                  "width":298,
                  "height":400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eef98b60d6224500967b1e5e7351d97a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":145},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c3a560b4234464eae47e006b6347634",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":145},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/file_downloading/u36.png"}},
{
          "id":"8d0a18f809eb4d458c9cef9483911b2b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":145},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eb06688e8354de08bf41328a8c21c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":145},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Image in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"image.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/file_downloading/u38.png"}},
{
          "id":"717d6339c66844ce967e10caa37aedf5",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'HelveticaNeue', 'Helvetica Neue'",
            "fontSize":"21px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":105,
              "y":144},
            "size":{
              "width":170,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1653176d64740e2b875206cedbb00b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                "fontSize":"21px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":105,
                  "y":144},
                "size":{
                  "width":170,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "4f5df35342ce47e0a30716c2b1172162":{
      "packageId":"4f5df35342ce47e0a30716c2b1172162",
      "type":"Axure:Master",
      "name":"File",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f8fe364db61b40c589f6166cd85bfb45",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800}},
            "adaptiveStyles":{
},
            "masterId":"a3c9ec5525e347978067bf5cebf60c89"},
{
            "id":"d02996b302f94de196808ad098565f5d",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800}},
            "adaptiveStyles":{
},
            "masterId":"a3c9ec5525e347978067bf5cebf60c89"},
{
            "id":"6cd27adeff834effb913419af64b9082",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":146},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ccd1491273c4165a10d56ef92b5046f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":38,
                    "y":146},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/link_email_with_cloud/u20.png"}},
{
            "id":"3917e2a098c54ce78a31db4a36b8cdec",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":42,
                "y":649},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1418b922e7a04d6692768abf16fb7ed0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":42,
                    "y":649},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/file_downloading/u21.png"}},
{
            "id":"9494e212d1a64bd2b72dd343067642dd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"24px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2087FC,
                "opacity":1},
              "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
              "location":{
                "x":310,
                "y":647},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f4b1324453ea48e287de22a15c9c90f5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"24px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2087FC,
                    "opacity":1},
                  "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
                  "location":{
                    "x":310,
                    "y":647},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"07455081423446c7aa510c348597326c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"24px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2087FC,
                "opacity":1},
              "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
              "location":{
                "x":133,
                "y":647},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d6c0788ac9f4a258a21c41c49fc53b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"24px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2087FC,
                    "opacity":1},
                  "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
                  "location":{
                    "x":133,
                    "y":647},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6ccab5e720024e1e9937120b4f6d59f3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":225,
                "y":647},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e90113a4a1454f21bbc164660dd17d27",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":225,
                    "y":647},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Note in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"note.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "annotation":{
              "Description":"Icon is filled in wiht color if there are note"},
            "images":{
              "normal~":"images/file_downloading/u27.png"}}]}},
    "a3c9ec5525e347978067bf5cebf60c89":{
      "packageId":"a3c9ec5525e347978067bf5cebf60c89",
      "type":"Axure:Master",
      "name":"EverDesk",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"12d11790695a4d9c8f38121434d74291",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc01043f76a74695a1cc1a0bab35dcd3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u1.png",
              "normal~":"images/first_launch/u1.png"}},
{
            "id":"9721dd10be0b4426b2d7c96348809de4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":32,
                "y":118},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a80150cd919b40c08ba799c9991e3be1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":32,
                    "y":118},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u3.png",
              "normal~":"images/first_launch/u3.png"}},
{
            "id":"bb5fc219776241398ba91074f14ee50b",
            "label":"text - h2",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"21px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":144,
                "y":130},
              "size":{
                "width":95,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81c1235877f9438b90a2592fa58a8e9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"21px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":144,
                    "y":130},
                  "size":{
                    "width":95,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cf16f2e09e2d4035bc19c2135d37a1d0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":37.5,
                "y":119},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8cf724cbd934951a4d73f1b37501249",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37.5,
                    "y":119},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u7.png",
              "normal~":"images/first_launch/u7.png"}}]}}},
  "objectPaths":{
    "ba61229ceb4c4f2d869715dcebe98d20":{
      "scriptId":"u0",
      "f8fe364db61b40c589f6166cd85bfb45":{
        "scriptId":"u1",
        "12d11790695a4d9c8f38121434d74291":{
          "scriptId":"u2"},
        "dc01043f76a74695a1cc1a0bab35dcd3":{
          "scriptId":"u3"},
        "9721dd10be0b4426b2d7c96348809de4":{
          "scriptId":"u4"},
        "a80150cd919b40c08ba799c9991e3be1":{
          "scriptId":"u5"},
        "bb5fc219776241398ba91074f14ee50b":{
          "scriptId":"u6"},
        "81c1235877f9438b90a2592fa58a8e9d":{
          "scriptId":"u7"},
        "cf16f2e09e2d4035bc19c2135d37a1d0":{
          "scriptId":"u8"},
        "d8cf724cbd934951a4d73f1b37501249":{
          "scriptId":"u9"}},
      "d02996b302f94de196808ad098565f5d":{
        "scriptId":"u10",
        "12d11790695a4d9c8f38121434d74291":{
          "scriptId":"u11"},
        "dc01043f76a74695a1cc1a0bab35dcd3":{
          "scriptId":"u12"},
        "9721dd10be0b4426b2d7c96348809de4":{
          "scriptId":"u13"},
        "a80150cd919b40c08ba799c9991e3be1":{
          "scriptId":"u14"},
        "bb5fc219776241398ba91074f14ee50b":{
          "scriptId":"u15"},
        "81c1235877f9438b90a2592fa58a8e9d":{
          "scriptId":"u16"},
        "cf16f2e09e2d4035bc19c2135d37a1d0":{
          "scriptId":"u17"},
        "d8cf724cbd934951a4d73f1b37501249":{
          "scriptId":"u18"}},
      "6cd27adeff834effb913419af64b9082":{
        "scriptId":"u19"},
      "9ccd1491273c4165a10d56ef92b5046f":{
        "scriptId":"u20"},
      "3917e2a098c54ce78a31db4a36b8cdec":{
        "scriptId":"u21"},
      "1418b922e7a04d6692768abf16fb7ed0":{
        "scriptId":"u22"},
      "9494e212d1a64bd2b72dd343067642dd":{
        "scriptId":"u23"},
      "f4b1324453ea48e287de22a15c9c90f5":{
        "scriptId":"u24"},
      "07455081423446c7aa510c348597326c":{
        "scriptId":"u25"},
      "3d6c0788ac9f4a258a21c41c49fc53b7":{
        "scriptId":"u26"},
      "6ccab5e720024e1e9937120b4f6d59f3":{
        "scriptId":"u27"},
      "e90113a4a1454f21bbc164660dd17d27":{
        "scriptId":"u28"}},
    "caa126b49f474f35a64fd8e9630fab14":{
      "scriptId":"u29"},
    "3bc87a5b10c746739bb7cb9508753026":{
      "scriptId":"u30"},
    "eef98b60d6224500967b1e5e7351d97a":{
      "scriptId":"u31"},
    "4c3a560b4234464eae47e006b6347634":{
      "scriptId":"u32"},
    "8d0a18f809eb4d458c9cef9483911b2b":{
      "scriptId":"u33"},
    "3eb06688e8354de08bf41328a8c21c63":{
      "scriptId":"u34"},
    "717d6339c66844ce967e10caa37aedf5":{
      "scriptId":"u35"},
    "d1653176d64740e2b875206cedbb00b2":{
      "scriptId":"u36"}}});