$axure.loadCurrentPage({
  "url":"forgot_password.html",
  "generationDate":new Date(1415446120670.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4890fb290d634e27b89ad879e4b0d8c4",
    "type":"Axure:Page",
    "name":"Forgot password",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7c9d28a611ee468e8d56111e4a4f35ec",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a3c9ec5525e347978067bf5cebf60c89"},
{
          "id":"10bc490a173e4aedb4f50a98d5d767f4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":151},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2978f68b1b9344fea3f595a811412f5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":151},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_up/u11.png"}},
{
          "id":"987ccb3c681c468b96133f207f3c1def",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'HelveticaNeue', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":97,
              "y":149},
            "size":{
              "width":186,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faddff0fe92f453e988a59534e140602",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":97,
                  "y":149},
                "size":{
                  "width":186,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f355b231ff247f09fa8f72e8f188676",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":40,
              "y":201},
            "size":{
              "width":299,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cca73fdf55b24ed3b37b0794835a198d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":40,
                  "y":201},
                "size":{
                  "width":299,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/forgot_password/u13.png"}},
{
          "id":"319979142ba9410d85401ca59637b303",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":80,
              "y":212},
            "size":{
              "width":63,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a9cf3ef3eb24bad93b8213f786eacaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":212},
                "size":{
                  "width":63,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b6834c7449a4110bd539d6d4dc5ba1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":211},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be5772329bf543be95eda24d647ccbf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":211},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_in/u21.png"}},
{
          "id":"9666441ce25b48b187006c134fb24573",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'HelveticaNeue', 'Helvetica Neue'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":282,
              "y":153},
            "size":{
              "width":58,
              "height":18},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"384204e03fc34cbc839f150221d34244",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":282,
                  "y":153},
                "size":{
                  "width":58,
                  "height":18},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4af4948b2ee24e5a89a748d74524aadc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":40,
              "y":251},
            "size":{
              "width":299,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9305043dc394873be495100eb557637",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":251},
                "size":{
                  "width":299,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1027943e9c64b399a9a80f1075ea72c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":474},
            "size":{
              "width":320,
              "height":216},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb5b692573724be2b35092b37b5f31d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":474},
                "size":{
                  "width":320,
                  "height":216},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_search/u95.png"}}]}},
  "masters":{
    "a3c9ec5525e347978067bf5cebf60c89":{
      "packageId":"a3c9ec5525e347978067bf5cebf60c89",
      "type":"Axure:Master",
      "name":"EverDesk",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"12d11790695a4d9c8f38121434d74291",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc01043f76a74695a1cc1a0bab35dcd3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u1.png"}},
{
            "id":"9721dd10be0b4426b2d7c96348809de4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":32,
                "y":118},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a80150cd919b40c08ba799c9991e3be1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":32,
                    "y":118},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u3.png"}},
{
            "id":"bb5fc219776241398ba91074f14ee50b",
            "label":"text - h2",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"21px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":144,
                "y":130},
              "size":{
                "width":95,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81c1235877f9438b90a2592fa58a8e9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"21px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":144,
                    "y":130},
                  "size":{
                    "width":95,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cf16f2e09e2d4035bc19c2135d37a1d0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":37.5,
                "y":119},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8cf724cbd934951a4d73f1b37501249",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37.5,
                    "y":119},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u7.png"}}]}}},
  "objectPaths":{
    "7c9d28a611ee468e8d56111e4a4f35ec":{
      "scriptId":"u0",
      "12d11790695a4d9c8f38121434d74291":{
        "scriptId":"u1"},
      "dc01043f76a74695a1cc1a0bab35dcd3":{
        "scriptId":"u2"},
      "9721dd10be0b4426b2d7c96348809de4":{
        "scriptId":"u3"},
      "a80150cd919b40c08ba799c9991e3be1":{
        "scriptId":"u4"},
      "bb5fc219776241398ba91074f14ee50b":{
        "scriptId":"u5"},
      "81c1235877f9438b90a2592fa58a8e9d":{
        "scriptId":"u6"},
      "cf16f2e09e2d4035bc19c2135d37a1d0":{
        "scriptId":"u7"},
      "d8cf724cbd934951a4d73f1b37501249":{
        "scriptId":"u8"}},
    "10bc490a173e4aedb4f50a98d5d767f4":{
      "scriptId":"u9"},
    "2978f68b1b9344fea3f595a811412f5b":{
      "scriptId":"u10"},
    "987ccb3c681c468b96133f207f3c1def":{
      "scriptId":"u11"},
    "faddff0fe92f453e988a59534e140602":{
      "scriptId":"u12"},
    "0f355b231ff247f09fa8f72e8f188676":{
      "scriptId":"u13"},
    "cca73fdf55b24ed3b37b0794835a198d":{
      "scriptId":"u14"},
    "319979142ba9410d85401ca59637b303":{
      "scriptId":"u15"},
    "0a9cf3ef3eb24bad93b8213f786eacaf":{
      "scriptId":"u16"},
    "5b6834c7449a4110bd539d6d4dc5ba1f":{
      "scriptId":"u17"},
    "be5772329bf543be95eda24d647ccbf0":{
      "scriptId":"u18"},
    "9666441ce25b48b187006c134fb24573":{
      "scriptId":"u19"},
    "384204e03fc34cbc839f150221d34244":{
      "scriptId":"u20"},
    "4af4948b2ee24e5a89a748d74524aadc":{
      "scriptId":"u21"},
    "e9305043dc394873be495100eb557637":{
      "scriptId":"u22"},
    "d1027943e9c64b399a9a80f1075ea72c":{
      "scriptId":"u23"},
    "cb5b692573724be2b35092b37b5f31d3":{
      "scriptId":"u24"}}});