$axure.loadCurrentPage({
  "url":"email_flilter.html",
  "generationDate":new Date(1415446118415.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3e31796cd9164c0ca7cfc1a7ba297717",
    "type":"Axure:Page",
    "name":"Email Flilter",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"10950e7db61c4294b2c51a5905a90308",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a3c9ec5525e347978067bf5cebf60c89"},
{
          "id":"5c4c956648d24b788694956d0c6becb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":119},
            "size":{
              "width":320,
              "height":61},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd78e3f009ae4587aa72fd2e68745a15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":119},
                "size":{
                  "width":320,
                  "height":61},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_search/u87.png"}},
{
          "id":"a8b9a65bab9a47f99d799063a7ec2064",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'HelveticaNeue', 'Helvetica Neue'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":282,
              "y":145},
            "size":{
              "width":58,
              "height":18},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf33a467cde545058b4a341f652ef34e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":282,
                  "y":145},
                "size":{
                  "width":58,
                  "height":18},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder content in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb59604b66ad4dcbb0684cceb5fa1b28",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d285de9778c245bd8a3604f971e3f921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_search/u91.png"}},
{
          "id":"4a7a7197363d41738c5f99e4bb264618",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":32,
              "y":180},
            "size":{
              "width":320,
              "height":509}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9ee232b53d044ebba6774fd1152af4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":32,
                  "y":180},
                "size":{
                  "width":320,
                  "height":509}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_search/u93.png"}},
{
          "id":"364c3b0d4bc24ba08b3f7594d82a00e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":469},
            "size":{
              "width":320,
              "height":216},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beed581fa9534911b2113be01760746d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":469},
                "size":{
                  "width":320,
                  "height":216},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_search/u95.png"}},
{
          "id":"49dfff1b12714cd78808484868cfd6a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":119},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f348c10339cd46368d25a2d693251644",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":119},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u7.png"}},
{
          "id":"b6b7b9b0660a412694274f0ae4eb4cde",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":180},
            "size":{
              "width":321,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"027e91e510ae4e93929be479abafc123",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":180},
                "size":{
                  "width":321,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_filter/u99.png"}},
{
          "id":"ef2ddff0f5e64b929c6f3c7b7b900d39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":82,
              "y":146},
            "size":{
              "width":38,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45b3d571f12b4b0c91c382cf7a215ebe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":82,
                  "y":146},
                "size":{
                  "width":38,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3796de305eed482d8a0ecd8648b14f9d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":146.5},
            "size":{
              "width":10,
              "height":16},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF2087FC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/folder_filter/u106_line.png"}},
{
          "id":"cedb6a3c7f5c4ca18985e4fccae4bd84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":291},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7a00d18f46f4906ab69f6c9b51a538a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":291},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u15.png"}},
{
          "id":"87d58278418347e3a37b2024229bcab7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":298},
            "size":{
              "width":228,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a409df81742d4a35b75f8b138f216fa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":298},
                "size":{
                  "width":228,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0779974a07d4e6790886d3b45e44ced",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":324},
            "size":{
              "width":312,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/add_cloud_account/u16_line.png"}},
{
          "id":"b113526712da437dafd3a59b1444f001",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE9E9E9},
            "location":{
              "x":34,
              "y":180},
            "size":{
              "width":318,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"063cef4349c54f18900179130b9d930a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE9E9E9},
                "location":{
                  "x":34,
                  "y":180},
                "size":{
                  "width":318,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/imap_pop3/u36.png"}},
{
          "id":"64605847364e43eebc404eac64ad8f18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":50,
              "y":183},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6c325865632401bb6a911056d80ec8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":183},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbf1fe261da94c588affee69e5466bb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE9E9E9},
            "location":{
              "x":34,
              "y":262},
            "size":{
              "width":318,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80be6db4201741dcbb398cfd0ac7a264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE9E9E9},
                "location":{
                  "x":34,
                  "y":262},
                "size":{
                  "width":318,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/imap_pop3/u36.png"}},
{
          "id":"52c238fdf6f34fdf93728af7d41d94d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":50,
              "y":265},
            "size":{
              "width":85,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98a157a11c71446b9c6f43400479ea83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":265},
                "size":{
                  "width":85,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8da5611bf5a440188db1c5d9bd2094af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":334},
            "size":{
              "width":40,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"480cfeeaf0304a0285b4358808fc1dfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":334},
                "size":{
                  "width":40,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_filter/u120.png"}},
{
          "id":"2f12d78011fa40039483b84b2877966e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":298},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8271c673a6594dc8b8ff6c3ee06593d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":298},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/root_folder_with_content/u27.png"}},
{
          "id":"b54aef39102346c4bc6b6d339ea8ff26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
            "location":{
              "x":118,
              "y":347},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9344521d09114e609227f5e649163dfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
                "location":{
                  "x":118,
                  "y":347},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c09fd5ea1a8144c8a0b418298b4aefc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":73,
              "y":206},
            "size":{
              "width":48,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c159daf764946928a28739c2ebde5cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":73,
                  "y":206},
                "size":{
                  "width":48,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2eaf84cb137c44dba4f090eb17405875",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":241,
              "y":206},
            "size":{
              "width":112,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"339a069797054a39a3e39af3402f4f1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":241,
                  "y":206},
                "size":{
                  "width":112,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9df1f1fcd7bf4f0fa6a47cd80d58f808",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":73,
              "y":236},
            "size":{
              "width":68,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a995f0ab95534bb3b7855929dc1d8de0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":73,
                  "y":236},
                "size":{
                  "width":68,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8435dcf80ed242e0a8d9a8cbeecc7b91",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":202},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acb1ac17e1a0404daf54b0d48b0a25b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":202},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_mass_actions/u55.png"}},
{
          "id":"d245f58df2a84f2e935c14cc1d6441e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":202},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6255b67a60e14a32aff9c768f2ae7b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":202},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_mass_actions/u55.png"}},
{
          "id":"36beddf3a1294c9fad447ec12fd15f5f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":255},
            "size":{
              "width":313,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder Filter Hidden in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_filter_hidden.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/folder_filter/u103_line.png"}},
{
          "id":"e113f7c2ef4c4fe1a9689930141c1b10",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":230},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13e4fabe6d304797b69cbb9416e88aa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":230},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_mass_actions/u55.png"}},
{
          "id":"3cb920184b714131a8a13f52f8113aa8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":230},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a50f8b3a18c7485cbb8c93bd6bec28c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":230},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_mass_actions/u53.png"}}]}},
  "masters":{
    "a3c9ec5525e347978067bf5cebf60c89":{
      "packageId":"a3c9ec5525e347978067bf5cebf60c89",
      "type":"Axure:Master",
      "name":"EverDesk",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"12d11790695a4d9c8f38121434d74291",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc01043f76a74695a1cc1a0bab35dcd3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u1.png"}},
{
            "id":"9721dd10be0b4426b2d7c96348809de4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":32,
                "y":118},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a80150cd919b40c08ba799c9991e3be1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":32,
                    "y":118},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u3.png"}},
{
            "id":"bb5fc219776241398ba91074f14ee50b",
            "label":"text - h2",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"21px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":144,
                "y":130},
              "size":{
                "width":95,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81c1235877f9438b90a2592fa58a8e9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"21px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":144,
                    "y":130},
                  "size":{
                    "width":95,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cf16f2e09e2d4035bc19c2135d37a1d0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":37.5,
                "y":119},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8cf724cbd934951a4d73f1b37501249",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37.5,
                    "y":119},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u7.png"}}]}}},
  "objectPaths":{
    "10950e7db61c4294b2c51a5905a90308":{
      "scriptId":"u0",
      "12d11790695a4d9c8f38121434d74291":{
        "scriptId":"u1"},
      "dc01043f76a74695a1cc1a0bab35dcd3":{
        "scriptId":"u2"},
      "9721dd10be0b4426b2d7c96348809de4":{
        "scriptId":"u3"},
      "a80150cd919b40c08ba799c9991e3be1":{
        "scriptId":"u4"},
      "bb5fc219776241398ba91074f14ee50b":{
        "scriptId":"u5"},
      "81c1235877f9438b90a2592fa58a8e9d":{
        "scriptId":"u6"},
      "cf16f2e09e2d4035bc19c2135d37a1d0":{
        "scriptId":"u7"},
      "d8cf724cbd934951a4d73f1b37501249":{
        "scriptId":"u8"}},
    "5c4c956648d24b788694956d0c6becb2":{
      "scriptId":"u9"},
    "cd78e3f009ae4587aa72fd2e68745a15":{
      "scriptId":"u10"},
    "a8b9a65bab9a47f99d799063a7ec2064":{
      "scriptId":"u11"},
    "cf33a467cde545058b4a341f652ef34e":{
      "scriptId":"u12"},
    "bb59604b66ad4dcbb0684cceb5fa1b28":{
      "scriptId":"u13"},
    "d285de9778c245bd8a3604f971e3f921":{
      "scriptId":"u14"},
    "4a7a7197363d41738c5f99e4bb264618":{
      "scriptId":"u15"},
    "e9ee232b53d044ebba6774fd1152af4b":{
      "scriptId":"u16"},
    "364c3b0d4bc24ba08b3f7594d82a00e5":{
      "scriptId":"u17"},
    "beed581fa9534911b2113be01760746d":{
      "scriptId":"u18"},
    "49dfff1b12714cd78808484868cfd6a2":{
      "scriptId":"u19"},
    "f348c10339cd46368d25a2d693251644":{
      "scriptId":"u20"},
    "b6b7b9b0660a412694274f0ae4eb4cde":{
      "scriptId":"u21"},
    "027e91e510ae4e93929be479abafc123":{
      "scriptId":"u22"},
    "ef2ddff0f5e64b929c6f3c7b7b900d39":{
      "scriptId":"u23"},
    "45b3d571f12b4b0c91c382cf7a215ebe":{
      "scriptId":"u24"},
    "3796de305eed482d8a0ecd8648b14f9d":{
      "scriptId":"u25"},
    "cedb6a3c7f5c4ca18985e4fccae4bd84":{
      "scriptId":"u26"},
    "a7a00d18f46f4906ab69f6c9b51a538a":{
      "scriptId":"u27"},
    "87d58278418347e3a37b2024229bcab7":{
      "scriptId":"u28"},
    "a409df81742d4a35b75f8b138f216fa3":{
      "scriptId":"u29"},
    "b0779974a07d4e6790886d3b45e44ced":{
      "scriptId":"u30"},
    "b113526712da437dafd3a59b1444f001":{
      "scriptId":"u31"},
    "063cef4349c54f18900179130b9d930a":{
      "scriptId":"u32"},
    "64605847364e43eebc404eac64ad8f18":{
      "scriptId":"u33"},
    "b6c325865632401bb6a911056d80ec8b":{
      "scriptId":"u34"},
    "cbf1fe261da94c588affee69e5466bb4":{
      "scriptId":"u35"},
    "80be6db4201741dcbb398cfd0ac7a264":{
      "scriptId":"u36"},
    "52c238fdf6f34fdf93728af7d41d94d5":{
      "scriptId":"u37"},
    "98a157a11c71446b9c6f43400479ea83":{
      "scriptId":"u38"},
    "8da5611bf5a440188db1c5d9bd2094af":{
      "scriptId":"u39"},
    "480cfeeaf0304a0285b4358808fc1dfd":{
      "scriptId":"u40"},
    "2f12d78011fa40039483b84b2877966e":{
      "scriptId":"u41"},
    "8271c673a6594dc8b8ff6c3ee06593d8":{
      "scriptId":"u42"},
    "b54aef39102346c4bc6b6d339ea8ff26":{
      "scriptId":"u43"},
    "9344521d09114e609227f5e649163dfb":{
      "scriptId":"u44"},
    "c09fd5ea1a8144c8a0b418298b4aefc7":{
      "scriptId":"u45"},
    "0c159daf764946928a28739c2ebde5cc":{
      "scriptId":"u46"},
    "2eaf84cb137c44dba4f090eb17405875":{
      "scriptId":"u47"},
    "339a069797054a39a3e39af3402f4f1f":{
      "scriptId":"u48"},
    "9df1f1fcd7bf4f0fa6a47cd80d58f808":{
      "scriptId":"u49"},
    "a995f0ab95534bb3b7855929dc1d8de0":{
      "scriptId":"u50"},
    "8435dcf80ed242e0a8d9a8cbeecc7b91":{
      "scriptId":"u51"},
    "acb1ac17e1a0404daf54b0d48b0a25b7":{
      "scriptId":"u52"},
    "d245f58df2a84f2e935c14cc1d6441e7":{
      "scriptId":"u53"},
    "6255b67a60e14a32aff9c768f2ae7b5c":{
      "scriptId":"u54"},
    "36beddf3a1294c9fad447ec12fd15f5f":{
      "scriptId":"u55"},
    "e113f7c2ef4c4fe1a9689930141c1b10":{
      "scriptId":"u56"},
    "13e4fabe6d304797b69cbb9416e88aa5":{
      "scriptId":"u57"},
    "3cb920184b714131a8a13f52f8113aa8":{
      "scriptId":"u58"},
    "a50f8b3a18c7485cbb8c93bd6bec28c2":{
      "scriptId":"u59"}}});