$axure.loadCurrentPage({
  "url":"warning_message.html",
  "generationDate":new Date(1415446120301.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b622f697d6b543319f984c623ed68209",
    "type":"Axure:Page",
    "name":"Warning Message",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"24ade118f5e94428859ada6496461f81",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6f8f3d412539455dbe4dbed5d56c9b25"},
{
          "id":"de545635d0c0464ea7e5801114b814f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":178},
            "size":{
              "width":320,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cad90dfd1f0f4c4f847482c4df046784",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":178},
                "size":{
                  "width":320,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/error_message/u87.png"}},
{
          "id":"70b589fabd694d349a42c6167287fc53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
            "location":{
              "x":80,
              "y":188},
            "size":{
              "width":260,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c130b2bca3a14bb7bf68eb2b2192e954",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
                "location":{
                  "x":80,
                  "y":188},
                "size":{
                  "width":260,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2224846fbdbf44bb91032fa249deb9ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
            "location":{
              "x":80,
              "y":208},
            "size":{
              "width":260,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"634c7715db214d1a8c0648220623b793",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
                "location":{
                  "x":80,
                  "y":208},
                "size":{
                  "width":260,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d3814a8c5254c6781073bc2024af1d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome', 'FontAwesome'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
            "location":{
              "x":39,
              "y":200},
            "size":{
              "width":37,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f52976680da8416883a539da10443795",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome', 'FontAwesome'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
                "location":{
                  "x":39,
                  "y":200},
                "size":{
                  "width":37,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "6f8f3d412539455dbe4dbed5d56c9b25":{
      "packageId":"6f8f3d412539455dbe4dbed5d56c9b25",
      "type":"Axure:Master",
      "name":"Folders List",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0d939d1d82d04b918bce047a82b448e9",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800}},
            "adaptiveStyles":{
},
            "masterId":"a3c9ec5525e347978067bf5cebf60c89"},
{
            "id":"9a6aa52d14bf4d8db8d897d57ebc828b",
            "label":"text - h2",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"21px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":105,
                "y":144},
              "size":{
                "width":170,
                "height":25},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45fb6d34dc854dd79c762e82744ce382",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"21px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":105,
                    "y":144},
                  "size":{
                    "width":170,
                    "height":25},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2a7169fd15a4426ba188946ff162e28d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":146.5},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f0b47799f0034d6fbf5bd47704b3f8f2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":38,
                    "y":146.5},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Root folder with content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"root_folder_with_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/link_email_with_cloud/u20.png"}},
{
            "id":"495952ac89604fa8b0ac375f984ad78f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":310,
                "y":153.5},
              "size":{
                "width":30,
                "height":6},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"323a49c1c48b4d728d18a304b7584c12",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":310,
                    "y":153.5},
                  "size":{
                    "width":30,
                    "height":6},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder Mass Actions in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_mass_actions.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/folder_content/u14.png"}},
{
            "id":"28dc24cd2d5e432cbf4944a9791eef09",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":314,
                "y":186},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9bf2d83bdba54492a480fc9a2579ee77",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":314,
                    "y":186},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder Actions in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_actions.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/root_folder_with_content/u27.png"}},
{
            "id":"29273eef759e4f33bd0dd78ca25761b5",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":314,
                "y":229},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"002a525b0afe4119925fc533e4b40800",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":314,
                    "y":229},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/root_folder_with_content/u27.png"}},
{
            "id":"3b734d0f831842a9aa621c4ec345f6a5",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":314,
                "y":275},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2cf6bf9988ad47f38e2c6f248bd7c04e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":314,
                    "y":275},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/root_folder_with_content/u27.png"}},
{
            "id":"e25dc7b48b1447d8982372770bf1ad9f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":314,
                "y":321},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"57c0b44d40fd417d9822a1d345344f1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":314,
                    "y":321},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/root_folder_with_content/u27.png"}},
{
            "id":"28484e2226234e3585b8b42f6c18843d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":314,
                "y":385},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99fe180bc8d54957aea6a3f3ce67357b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":314,
                    "y":385},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/root_folder_with_content/u27.png"}},
{
            "id":"9d1adebb71a34f12a3b4e96b818723ca",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":314,
                "y":428},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c3098ba5d16842e48207af9087c4ab34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":314,
                    "y":428},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/root_folder_with_content/u27.png"}},
{
            "id":"f6bca795bbea443bb368ac5a6372c2ca",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":314,
                "y":471},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54b321cd9888435fa017e67bc956932b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":314,
                    "y":471},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/root_folder_with_content/u27.png"}},
{
            "id":"c18fb70dc4924606b2348797334b59d1",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":33,
                "y":182}},
            "adaptiveStyles":{
},
            "masterId":"b6a6a21b6e8345489b1ff49c557b5354"},
{
            "id":"3bff1b87e39a4521bce306732b395eef",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":32,
                "y":635}},
            "adaptiveStyles":{
},
            "masterId":"d89314f89a58461fa7ad6fe92cbb66a9"}]}},
    "a3c9ec5525e347978067bf5cebf60c89":{
      "packageId":"a3c9ec5525e347978067bf5cebf60c89",
      "type":"Axure:Master",
      "name":"EverDesk",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"12d11790695a4d9c8f38121434d74291",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc01043f76a74695a1cc1a0bab35dcd3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u1.png"}},
{
            "id":"9721dd10be0b4426b2d7c96348809de4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":32,
                "y":118},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a80150cd919b40c08ba799c9991e3be1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":32,
                    "y":118},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u3.png"}},
{
            "id":"bb5fc219776241398ba91074f14ee50b",
            "label":"text - h2",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"21px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":144,
                "y":130},
              "size":{
                "width":95,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81c1235877f9438b90a2592fa58a8e9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"21px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":144,
                    "y":130},
                  "size":{
                    "width":95,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cf16f2e09e2d4035bc19c2135d37a1d0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":37.5,
                "y":119},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8cf724cbd934951a4d73f1b37501249",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37.5,
                    "y":119},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u7.png"}}]}},
    "b6a6a21b6e8345489b1ff49c557b5354":{
      "packageId":"b6a6a21b6e8345489b1ff49c557b5354",
      "type":"Axure:Master",
      "name":"Folder Table",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"edfc2f4ce39745e1bf776d40ceea8f59",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":46},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dcc53fc4119c489ba4c4387a5ce5891d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":46},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"d8ebf613679243f98e5e301233784516",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":53},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"32ce2f1906d844189558c2f8a34fe123",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":53},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9affdfe40f654aa397ff2597ae37939b",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":79},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"c1ff910c9c7348fba65de05303d26a24",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":89},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4fbc2d421ba1461dbe178b75808824c2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":89},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"fbd97f546dc54b009c185aa832f6466a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":96},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d42d5d8bb2224092a300e745105c635d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":96},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9f14d206462e48b9b40bab12bba2d31d",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":122},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"d085552437cb4a2097533f961c404969",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":132},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e7346c892eb49b68ad04ac33e1f7f1d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":132},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"86b2d89a36f844a38dd221378968b405",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":139},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"28776cc25a17427b95cd43b610efee10",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":139},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7ea28152c03941299e4f169d094ebd59",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":165},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"eacf152fe7754c0d9e032fb59580759a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE9E9E9},
              "location":{
                "x":0,
                "y":172},
              "size":{
                "width":318,
                "height":22},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"62e224545cd44e458675e6da3eaa401b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE9E9E9},
                  "location":{
                    "x":0,
                    "y":172},
                  "size":{
                    "width":318,
                    "height":22},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/imap_pop3/u36.png"}},
{
            "id":"5124ca61545c4c17b645962eaaca0a46",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":16,
                "y":175},
              "size":{
                "width":29,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9245ee5ad6e4a31bd45ffd7a8579ee8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":16,
                    "y":175},
                  "size":{
                    "width":29,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3dc96932814c4e3bb92028225f4c9569",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":196},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfe85946c4db4df29374b8393d5e1ade",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":196},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"85b8630675134bc8b54e71921db21891",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":203},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0e15ad3662b14c369cdbac7ef4e96e5d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":203},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open File Downloading in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"file_downloading.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cbd8267cf4044508b19c8b2ad0c72e9a",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":229},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"39ea4dbb62c847e7816e41fa39a663f8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":239},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1eae7af5be7d42278105e53ad6180c5c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":239},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"09df8f3ac6344f6782c35cdd4e133340",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":246},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d985f851eead4807900589566e27ebee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":246},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Image in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"image.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8b2275de79fe4c27aba0ba15fa76752a",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":272},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"4355a551ad1b4242a44a2412753f8dc6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":282},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31dc927d10a74775bc9034e48c217a52",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":282},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"26aa636b545c4947ae36bf3df06893fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":282},
              "size":{
                "width":171,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0cac14fb90ee449bbfa615b84da9d38c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":282},
                  "size":{
                    "width":171,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open E-mail in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"e-mail.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ea4f935cf86b4c24a908c261333b946c",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":315},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"3c79410579c2493eb7cbedd74d84920f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":0},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7902d20f41f740a487e03bac900c7603",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":0},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"e5d19c2b92ec4c9789da2cea3a74fe91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":7},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a47e22c85df346839de86e05679962ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":7},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7d1c2fea52054efea49aef8961aef751",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":33},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"4877d59f4c7b44c2bb6800ab1b3df9b2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":301},
              "size":{
                "width":251,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d49a78d46e25494a900cb6d5274956cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":301},
                  "size":{
                    "width":251,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open E-mail in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"e-mail.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "d89314f89a58461fa7ad6fe92cbb66a9":{
      "packageId":"d89314f89a58461fa7ad6fe92cbb66a9",
      "type":"Axure:Master",
      "name":"Tabbar",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"49ed5d571ebc47deb5cebc13c668cf56",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":51},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee972d7e6bce42a7be40a4cec819d967",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":51},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u13.png"}},
{
            "id":"5e1f04ce81654c5499486eefac74ea97",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":143,
                "y":4},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0e0bddaa66bf446ea4e833d29316d0e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":143,
                    "y":4},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Root folder with content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"root_folder_with_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"67a5021058454d6a839becccbdc39e43",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF4478FB,
                "opacity":1},
              "location":{
                "x":122,
                "y":36},
              "size":{
                "width":73,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9e38759bdf44e298e31bf83cca565a1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF4478FB,
                    "opacity":1},
                  "location":{
                    "x":122,
                    "y":36},
                  "size":{
                    "width":73,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0993f26346014d4bb26856d5e5d1db8d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":25,
                "y":4},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"066c9b84b33240389b02efaced716c90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":25,
                    "y":4},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Favorites in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"favorites.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"760cf6f4d7e14daeacd018ba740d47bb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":11,
                "y":36},
              "size":{
                "width":58,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9766b0c194e4a29a9492e090163ebc9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":11,
                    "y":36},
                  "size":{
                    "width":58,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"655d64d13b9e426fac601ad145b3f715",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":270,
                "y":4},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7d931fa140ed4a7796b1f5c6b18b54a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":270,
                    "y":4},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"af93c72b1694414587a00604ec54d3dd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":262,
                "y":36},
              "size":{
                "width":45,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dffe95781d8b4c599a60053760cdfe99",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":262,
                    "y":36},
                  "size":{
                    "width":45,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "24ade118f5e94428859ada6496461f81":{
      "scriptId":"u0",
      "0d939d1d82d04b918bce047a82b448e9":{
        "scriptId":"u1",
        "12d11790695a4d9c8f38121434d74291":{
          "scriptId":"u2"},
        "dc01043f76a74695a1cc1a0bab35dcd3":{
          "scriptId":"u3"},
        "9721dd10be0b4426b2d7c96348809de4":{
          "scriptId":"u4"},
        "a80150cd919b40c08ba799c9991e3be1":{
          "scriptId":"u5"},
        "bb5fc219776241398ba91074f14ee50b":{
          "scriptId":"u6"},
        "81c1235877f9438b90a2592fa58a8e9d":{
          "scriptId":"u7"},
        "cf16f2e09e2d4035bc19c2135d37a1d0":{
          "scriptId":"u8"},
        "d8cf724cbd934951a4d73f1b37501249":{
          "scriptId":"u9"}},
      "9a6aa52d14bf4d8db8d897d57ebc828b":{
        "scriptId":"u10"},
      "45fb6d34dc854dd79c762e82744ce382":{
        "scriptId":"u11"},
      "2a7169fd15a4426ba188946ff162e28d":{
        "scriptId":"u12"},
      "f0b47799f0034d6fbf5bd47704b3f8f2":{
        "scriptId":"u13"},
      "495952ac89604fa8b0ac375f984ad78f":{
        "scriptId":"u14"},
      "323a49c1c48b4d728d18a304b7584c12":{
        "scriptId":"u15"},
      "28dc24cd2d5e432cbf4944a9791eef09":{
        "scriptId":"u16"},
      "9bf2d83bdba54492a480fc9a2579ee77":{
        "scriptId":"u17"},
      "29273eef759e4f33bd0dd78ca25761b5":{
        "scriptId":"u18"},
      "002a525b0afe4119925fc533e4b40800":{
        "scriptId":"u19"},
      "3b734d0f831842a9aa621c4ec345f6a5":{
        "scriptId":"u20"},
      "2cf6bf9988ad47f38e2c6f248bd7c04e":{
        "scriptId":"u21"},
      "e25dc7b48b1447d8982372770bf1ad9f":{
        "scriptId":"u22"},
      "57c0b44d40fd417d9822a1d345344f1a":{
        "scriptId":"u23"},
      "28484e2226234e3585b8b42f6c18843d":{
        "scriptId":"u24"},
      "99fe180bc8d54957aea6a3f3ce67357b":{
        "scriptId":"u25"},
      "9d1adebb71a34f12a3b4e96b818723ca":{
        "scriptId":"u26"},
      "c3098ba5d16842e48207af9087c4ab34":{
        "scriptId":"u27"},
      "f6bca795bbea443bb368ac5a6372c2ca":{
        "scriptId":"u28"},
      "54b321cd9888435fa017e67bc956932b":{
        "scriptId":"u29"},
      "c18fb70dc4924606b2348797334b59d1":{
        "scriptId":"u30",
        "edfc2f4ce39745e1bf776d40ceea8f59":{
          "scriptId":"u31"},
        "dcc53fc4119c489ba4c4387a5ce5891d":{
          "scriptId":"u32"},
        "d8ebf613679243f98e5e301233784516":{
          "scriptId":"u33"},
        "32ce2f1906d844189558c2f8a34fe123":{
          "scriptId":"u34"},
        "9affdfe40f654aa397ff2597ae37939b":{
          "scriptId":"u35"},
        "c1ff910c9c7348fba65de05303d26a24":{
          "scriptId":"u36"},
        "4fbc2d421ba1461dbe178b75808824c2":{
          "scriptId":"u37"},
        "fbd97f546dc54b009c185aa832f6466a":{
          "scriptId":"u38"},
        "d42d5d8bb2224092a300e745105c635d":{
          "scriptId":"u39"},
        "9f14d206462e48b9b40bab12bba2d31d":{
          "scriptId":"u40"},
        "d085552437cb4a2097533f961c404969":{
          "scriptId":"u41"},
        "6e7346c892eb49b68ad04ac33e1f7f1d":{
          "scriptId":"u42"},
        "86b2d89a36f844a38dd221378968b405":{
          "scriptId":"u43"},
        "28776cc25a17427b95cd43b610efee10":{
          "scriptId":"u44"},
        "7ea28152c03941299e4f169d094ebd59":{
          "scriptId":"u45"},
        "eacf152fe7754c0d9e032fb59580759a":{
          "scriptId":"u46"},
        "62e224545cd44e458675e6da3eaa401b":{
          "scriptId":"u47"},
        "5124ca61545c4c17b645962eaaca0a46":{
          "scriptId":"u48"},
        "b9245ee5ad6e4a31bd45ffd7a8579ee8":{
          "scriptId":"u49"},
        "3dc96932814c4e3bb92028225f4c9569":{
          "scriptId":"u50"},
        "cfe85946c4db4df29374b8393d5e1ade":{
          "scriptId":"u51"},
        "85b8630675134bc8b54e71921db21891":{
          "scriptId":"u52"},
        "0e15ad3662b14c369cdbac7ef4e96e5d":{
          "scriptId":"u53"},
        "cbd8267cf4044508b19c8b2ad0c72e9a":{
          "scriptId":"u54"},
        "39ea4dbb62c847e7816e41fa39a663f8":{
          "scriptId":"u55"},
        "1eae7af5be7d42278105e53ad6180c5c":{
          "scriptId":"u56"},
        "09df8f3ac6344f6782c35cdd4e133340":{
          "scriptId":"u57"},
        "d985f851eead4807900589566e27ebee":{
          "scriptId":"u58"},
        "8b2275de79fe4c27aba0ba15fa76752a":{
          "scriptId":"u59"},
        "4355a551ad1b4242a44a2412753f8dc6":{
          "scriptId":"u60"},
        "31dc927d10a74775bc9034e48c217a52":{
          "scriptId":"u61"},
        "26aa636b545c4947ae36bf3df06893fe":{
          "scriptId":"u62"},
        "0cac14fb90ee449bbfa615b84da9d38c":{
          "scriptId":"u63"},
        "ea4f935cf86b4c24a908c261333b946c":{
          "scriptId":"u64"},
        "3c79410579c2493eb7cbedd74d84920f":{
          "scriptId":"u65"},
        "7902d20f41f740a487e03bac900c7603":{
          "scriptId":"u66"},
        "e5d19c2b92ec4c9789da2cea3a74fe91":{
          "scriptId":"u67"},
        "a47e22c85df346839de86e05679962ba":{
          "scriptId":"u68"},
        "7d1c2fea52054efea49aef8961aef751":{
          "scriptId":"u69"},
        "4877d59f4c7b44c2bb6800ab1b3df9b2":{
          "scriptId":"u70"},
        "d49a78d46e25494a900cb6d5274956cb":{
          "scriptId":"u71"}},
      "3bff1b87e39a4521bce306732b395eef":{
        "scriptId":"u72",
        "49ed5d571ebc47deb5cebc13c668cf56":{
          "scriptId":"u73"},
        "ee972d7e6bce42a7be40a4cec819d967":{
          "scriptId":"u74"},
        "5e1f04ce81654c5499486eefac74ea97":{
          "scriptId":"u75"},
        "0e0bddaa66bf446ea4e833d29316d0e3":{
          "scriptId":"u76"},
        "67a5021058454d6a839becccbdc39e43":{
          "scriptId":"u77"},
        "e9e38759bdf44e298e31bf83cca565a1":{
          "scriptId":"u78"},
        "0993f26346014d4bb26856d5e5d1db8d":{
          "scriptId":"u79"},
        "066c9b84b33240389b02efaced716c90":{
          "scriptId":"u80"},
        "760cf6f4d7e14daeacd018ba740d47bb":{
          "scriptId":"u81"},
        "e9766b0c194e4a29a9492e090163ebc9":{
          "scriptId":"u82"},
        "655d64d13b9e426fac601ad145b3f715":{
          "scriptId":"u83"},
        "7d931fa140ed4a7796b1f5c6b18b54a4":{
          "scriptId":"u84"},
        "af93c72b1694414587a00604ec54d3dd":{
          "scriptId":"u85"},
        "dffe95781d8b4c599a60053760cdfe99":{
          "scriptId":"u86"}}},
    "de545635d0c0464ea7e5801114b814f2":{
      "scriptId":"u87"},
    "cad90dfd1f0f4c4f847482c4df046784":{
      "scriptId":"u88"},
    "70b589fabd694d349a42c6167287fc53":{
      "scriptId":"u89"},
    "c130b2bca3a14bb7bf68eb2b2192e954":{
      "scriptId":"u90"},
    "2224846fbdbf44bb91032fa249deb9ab":{
      "scriptId":"u91"},
    "634c7715db214d1a8c0648220623b793":{
      "scriptId":"u92"},
    "2d3814a8c5254c6781073bc2024af1d6":{
      "scriptId":"u93"},
    "f52976680da8416883a539da10443795":{
      "scriptId":"u94"}}});