$axure.loadCurrentPage({
  "url":"e-mail_thread.html",
  "generationDate":new Date(1415447467548.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2b014fa7b9cc41708bc46b0d817ba28e",
    "type":"Axure:Page",
    "name":"E-mail thread",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"da122178e84f4344bdc50de9007056f6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a3c9ec5525e347978067bf5cebf60c89"},
{
          "id":"4691f03b491747a8911aac2d25aa05d9",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'HelveticaNeue', 'Helvetica Neue'",
            "fontSize":"21px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":105,
              "y":144},
            "size":{
              "width":170,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3131bcfc15f54709a5eccd7837d0ccf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                "fontSize":"21px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":105,
                  "y":144},
                "size":{
                  "width":170,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"999cf06d439c48d7a3d6a4c31979b66c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":146.5},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9a6d5e0e02f4f9d8cba763cec278ac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":146.5},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder content in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/link_email_with_cloud/u20.png"}},
{
          "id":"775a59d1174a4854a84e12abf7c4194d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":153.5},
            "size":{
              "width":30,
              "height":6},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bf36579491b4eb3af26533138ba8aaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":153.5},
                "size":{
                  "width":30,
                  "height":6},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_content/u14.png"}},
{
          "id":"2e7d660b254f4e02841da60b04ffda6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":204},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae9a155af8d846009ce6794bb220df4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":204},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u15.png"}},
{
          "id":"547c7d65a12648fda5d11e6413f3899a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":204},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2add68852f6b41f09c0e0242ce802023",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":204},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open E-mail in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"e-mail.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6bcfd20a371457095a73456ed246fa0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":237},
            "size":{
              "width":312,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/add_cloud_account/u16_line.png"}},
{
          "id":"f6b37ce2d5634f0885dafcde44211c18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":223},
            "size":{
              "width":251,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d8395a8a04848f8a7395ac15cde1a1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":223},
                "size":{
                  "width":251,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open E-mail in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"e-mail.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7838731fef754fd6a92d25fa3b0483c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":247},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31b5167de2ea4a0dbeae500e99e7cd09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":247},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u15.png"}},
{
          "id":"17ca3660645449119b8c4d24024acf85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":247},
            "size":{
              "width":171,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5682b4f49b9647cd8618f4cc5447ee52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":247},
                "size":{
                  "width":171,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open E-mail in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"e-mail.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0587014806c4f8b94ed9ad1500f4935",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":280},
            "size":{
              "width":312,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/add_cloud_account/u16_line.png"}},
{
          "id":"f33c48e41524434c9ab11a86a8ce5ee1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":266},
            "size":{
              "width":251,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4a9a49e440c43f28a073f76ee6f7b36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":266},
                "size":{
                  "width":251,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open E-mail in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"e-mail.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e9f95a85015435c8514d41803ce6591",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":290},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bee439e4526483a82da03cad8b2e506",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":290},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u15.png"}},
{
          "id":"aa8e21bf86624e0cb5c09a04fd713582",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":290},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cb3524c82b944d8aa4dff3a3fec7cae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":290},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open E-mail in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"e-mail.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e80c1791868c4e45bac1b3353303511f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":323},
            "size":{
              "width":312,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/add_cloud_account/u16_line.png"}},
{
          "id":"eef4c7fce38c4d8e8ce3cc982e6d1cfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":309},
            "size":{
              "width":251,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3013d23dc7f4b91bca57e90f7f8020d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":309},
                "size":{
                  "width":251,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open E-mail in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"e-mail.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c16eb975736a4883b162070821f54673",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE9E9E9},
            "location":{
              "x":34,
              "y":179},
            "size":{
              "width":318,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaf2c9170081488980430e4b4f6a82b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE9E9E9},
                "location":{
                  "x":34,
                  "y":179},
                "size":{
                  "width":318,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/imap_pop3/u36.png"}},
{
          "id":"4caeaf1c289349b1969ebe82644e7acf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":50,
              "y":182},
            "size":{
              "width":149,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2b144f6e4f747fda0bd9cfb3e2d9276",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":182},
                "size":{
                  "width":149,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "a3c9ec5525e347978067bf5cebf60c89":{
      "packageId":"a3c9ec5525e347978067bf5cebf60c89",
      "type":"Axure:Master",
      "name":"EverDesk",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"12d11790695a4d9c8f38121434d74291",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc01043f76a74695a1cc1a0bab35dcd3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u1.png"}},
{
            "id":"9721dd10be0b4426b2d7c96348809de4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":32,
                "y":118},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a80150cd919b40c08ba799c9991e3be1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":32,
                    "y":118},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u3.png"}},
{
            "id":"bb5fc219776241398ba91074f14ee50b",
            "label":"text - h2",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"21px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":144,
                "y":130},
              "size":{
                "width":95,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81c1235877f9438b90a2592fa58a8e9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"21px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":144,
                    "y":130},
                  "size":{
                    "width":95,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cf16f2e09e2d4035bc19c2135d37a1d0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":37.5,
                "y":119},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8cf724cbd934951a4d73f1b37501249",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37.5,
                    "y":119},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u7.png"}}]}}},
  "objectPaths":{
    "da122178e84f4344bdc50de9007056f6":{
      "scriptId":"u0",
      "12d11790695a4d9c8f38121434d74291":{
        "scriptId":"u1"},
      "dc01043f76a74695a1cc1a0bab35dcd3":{
        "scriptId":"u2"},
      "9721dd10be0b4426b2d7c96348809de4":{
        "scriptId":"u3"},
      "a80150cd919b40c08ba799c9991e3be1":{
        "scriptId":"u4"},
      "bb5fc219776241398ba91074f14ee50b":{
        "scriptId":"u5"},
      "81c1235877f9438b90a2592fa58a8e9d":{
        "scriptId":"u6"},
      "cf16f2e09e2d4035bc19c2135d37a1d0":{
        "scriptId":"u7"},
      "d8cf724cbd934951a4d73f1b37501249":{
        "scriptId":"u8"}},
    "4691f03b491747a8911aac2d25aa05d9":{
      "scriptId":"u9"},
    "3131bcfc15f54709a5eccd7837d0ccf4":{
      "scriptId":"u10"},
    "999cf06d439c48d7a3d6a4c31979b66c":{
      "scriptId":"u11"},
    "c9a6d5e0e02f4f9d8cba763cec278ac3":{
      "scriptId":"u12"},
    "775a59d1174a4854a84e12abf7c4194d":{
      "scriptId":"u13"},
    "5bf36579491b4eb3af26533138ba8aaf":{
      "scriptId":"u14"},
    "2e7d660b254f4e02841da60b04ffda6b":{
      "scriptId":"u15"},
    "ae9a155af8d846009ce6794bb220df4c":{
      "scriptId":"u16"},
    "547c7d65a12648fda5d11e6413f3899a":{
      "scriptId":"u17"},
    "2add68852f6b41f09c0e0242ce802023":{
      "scriptId":"u18"},
    "a6bcfd20a371457095a73456ed246fa0":{
      "scriptId":"u19"},
    "f6b37ce2d5634f0885dafcde44211c18":{
      "scriptId":"u20"},
    "3d8395a8a04848f8a7395ac15cde1a1f":{
      "scriptId":"u21"},
    "7838731fef754fd6a92d25fa3b0483c7":{
      "scriptId":"u22"},
    "31b5167de2ea4a0dbeae500e99e7cd09":{
      "scriptId":"u23"},
    "17ca3660645449119b8c4d24024acf85":{
      "scriptId":"u24"},
    "5682b4f49b9647cd8618f4cc5447ee52":{
      "scriptId":"u25"},
    "a0587014806c4f8b94ed9ad1500f4935":{
      "scriptId":"u26"},
    "f33c48e41524434c9ab11a86a8ce5ee1":{
      "scriptId":"u27"},
    "e4a9a49e440c43f28a073f76ee6f7b36":{
      "scriptId":"u28"},
    "4e9f95a85015435c8514d41803ce6591":{
      "scriptId":"u29"},
    "7bee439e4526483a82da03cad8b2e506":{
      "scriptId":"u30"},
    "aa8e21bf86624e0cb5c09a04fd713582":{
      "scriptId":"u31"},
    "0cb3524c82b944d8aa4dff3a3fec7cae":{
      "scriptId":"u32"},
    "e80c1791868c4e45bac1b3353303511f":{
      "scriptId":"u33"},
    "eef4c7fce38c4d8e8ce3cc982e6d1cfd":{
      "scriptId":"u34"},
    "a3013d23dc7f4b91bca57e90f7f8020d":{
      "scriptId":"u35"},
    "c16eb975736a4883b162070821f54673":{
      "scriptId":"u36"},
    "eaf2c9170081488980430e4b4f6a82b0":{
      "scriptId":"u37"},
    "4caeaf1c289349b1969ebe82644e7acf":{
      "scriptId":"u38"},
    "b2b144f6e4f747fda0bd9cfb3e2d9276":{
      "scriptId":"u39"}}});