$axure.loadCurrentPage({
  "url":"select_move_target.html",
  "generationDate":new Date(1415447466056.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"33ffe55e90fb456b86c31191ff71788e",
    "type":"Axure:Page",
    "name":"Select Move target",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8d15481846d8411083b43ffb9c61c32c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "size":{
              "width":380,
              "height":800}},
          "adaptiveStyles":{
},
          "masterId":"a3c9ec5525e347978067bf5cebf60c89"},
{
          "id":"8a77f53d8b4a427ca37c9ac28e4cb723",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":228},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7893aa998c19465294ccf1ac9dbc03c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":228},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u15.png"}},
{
          "id":"aa4f19340201401ba3ccfca1b96e90d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":235},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a52782d5c5a43578ebb4630ae1f1da0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":235},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder content in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4892cbdf32e46e18999e5ee29a3ed88",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":261},
            "size":{
              "width":312,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/add_cloud_account/u16_line.png"}},
{
          "id":"95280eb6c20d4b1e8897a05458417593",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":271},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2288d6a9cef4d38b6276f8c0c05fdcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":271},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u15.png"}},
{
          "id":"45e124c998e64c249612d51dcf164bb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":278},
            "size":{
              "width":260,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"636f7d6fdf3d4d878543fd3c31e25f83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":278},
                "size":{
                  "width":260,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder content in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"651d49bbd2d14a729c23f78fbb2d8e72",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":304},
            "size":{
              "width":312,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/add_cloud_account/u16_line.png"}},
{
          "id":"d86233ba748c4b21b359a78ec5a2f26f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":314},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce6e64d74f4d429d994d3ad7ff52597c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":314},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u15.png"}},
{
          "id":"c151c5321e664528bf58e4e7ee0b0323",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":321},
            "size":{
              "width":260,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce12f77ec1f64460aa3801670794ee90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":321},
                "size":{
                  "width":260,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder content in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbc117d9a32f4008969dfb66455a3635",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":347},
            "size":{
              "width":312,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/add_cloud_account/u16_line.png"}},
{
          "id":"885e0fd9fe2d445fb42752c1dd953472",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE9E9E9},
            "location":{
              "x":33,
              "y":354},
            "size":{
              "width":318,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccd62a2408a0451c82debe39fb4eaa9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE9E9E9},
                "location":{
                  "x":33,
                  "y":354},
                "size":{
                  "width":318,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/imap_pop3/u36.png"}},
{
          "id":"c4d31a05fdf141ae8cc20504a1581927",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":49,
              "y":357},
            "size":{
              "width":29,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7945509586f848d1876d67ea5579b760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":49,
                  "y":357},
                "size":{
                  "width":29,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88e5fc5fa4854499ae95cfb1d467c469",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":378},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7a9e715d1044f86bd38049ef42cc3e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":378},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u15.png"}},
{
          "id":"626647c28dd04a7a87b12feb91577fa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":385},
            "size":{
              "width":260,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3c8c5b5a6a34d7e874442c715ae87d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":385},
                "size":{
                  "width":260,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder content in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed047f9d6a1b4176a899a9a361fbb180",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":411},
            "size":{
              "width":312,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/add_cloud_account/u16_line.png"}},
{
          "id":"87fed5770f72431fa0d29565281ab66e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":421},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"690415de3bac4ee78b52d73783324d04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":421},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u15.png"}},
{
          "id":"9d27d4dac9c64480b6628e25d576d2d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":428},
            "size":{
              "width":260,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2debf5e416854209ad9f1dfc61a28893",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":428},
                "size":{
                  "width":260,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder content in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"495840792abe4bfc8e4317f1efeb348b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":454},
            "size":{
              "width":312,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/add_cloud_account/u16_line.png"}},
{
          "id":"31300a90148a4d7cbb4d569ea7721d89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":464},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"985f8f90348d4941913dead9a90c76e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":464},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u15.png"}},
{
          "id":"5b7ac762b20d4e24821522059377fb9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":471},
            "size":{
              "width":260,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74e62e04a7be4ee381ff484751878b9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":471},
                "size":{
                  "width":260,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder content in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db4398fe026b4ceda6085bb65064d0a7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":497},
            "size":{
              "width":312,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/add_cloud_account/u16_line.png"}},
{
          "id":"6c9a91bc5b7f452ca9f76f374b3de5f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":182},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"375ba7a0e41c41259249ea2d5e97c8c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":182},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/first_launch/u15.png"}},
{
          "id":"e2a775d3360a402eba72725e5ed01b4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":189},
            "size":{
              "width":222,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2e67366fc8b4265a1cf0832768020b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":189},
                "size":{
                  "width":222,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder content in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb59c429b0024fa4875457dff9cb87bf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":215},
            "size":{
              "width":312,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/add_cloud_account/u16_line.png"}},
{
          "id":"5e8386ecfdc74cf984f3de50d1e5f390",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'HelveticaNeue', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":87,
              "y":142},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f5647afc6874166b89feb04aefa967f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":87,
                  "y":142},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/select_move_target/u48.png"}},
{
          "id":"b1fd117c0a6e4bc3acf89a2175a035db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'HelveticaNeue', 'Helvetica Neue'",
            "fontSize":"16px",
            "baseStyle":"fe2f353aa2c746628fee9754f4754197",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":37,
              "y":142},
            "size":{
              "width":70,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88d0c84a17e845d19618be3e958f1693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                "fontSize":"16px",
                "baseStyle":"fe2f353aa2c746628fee9754f4754197",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":37,
                  "y":142},
                "size":{
                  "width":70,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder Mass Actions in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_mass_actions.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/select_move_target/u50.png"}},
{
          "id":"31321709edc24e9bb603ff316642e146",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'HelveticaNeue', 'Helvetica Neue'",
            "fontSize":"16px",
            "baseStyle":"fe2f353aa2c746628fee9754f4754197",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":279,
              "y":142},
            "size":{
              "width":70,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5dc5e5b96364a99a83d026e943038e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                "fontSize":"16px",
                "baseStyle":"fe2f353aa2c746628fee9754f4754197",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":279,
                  "y":142},
                "size":{
                  "width":70,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Folder content in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"folder_content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/select_move_target/u50.png"}}]}},
  "masters":{
    "a3c9ec5525e347978067bf5cebf60c89":{
      "packageId":"a3c9ec5525e347978067bf5cebf60c89",
      "type":"Axure:Master",
      "name":"EverDesk",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"12d11790695a4d9c8f38121434d74291",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc01043f76a74695a1cc1a0bab35dcd3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u1.png"}},
{
            "id":"9721dd10be0b4426b2d7c96348809de4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":32,
                "y":118},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a80150cd919b40c08ba799c9991e3be1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":32,
                    "y":118},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u3.png"}},
{
            "id":"bb5fc219776241398ba91074f14ee50b",
            "label":"text - h2",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"21px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":144,
                "y":130},
              "size":{
                "width":95,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81c1235877f9438b90a2592fa58a8e9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"21px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":144,
                    "y":130},
                  "size":{
                    "width":95,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cf16f2e09e2d4035bc19c2135d37a1d0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":37.5,
                "y":119},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8cf724cbd934951a4d73f1b37501249",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37.5,
                    "y":119},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u7.png"}}]}}},
  "objectPaths":{
    "8d15481846d8411083b43ffb9c61c32c":{
      "scriptId":"u0",
      "12d11790695a4d9c8f38121434d74291":{
        "scriptId":"u1"},
      "dc01043f76a74695a1cc1a0bab35dcd3":{
        "scriptId":"u2"},
      "9721dd10be0b4426b2d7c96348809de4":{
        "scriptId":"u3"},
      "a80150cd919b40c08ba799c9991e3be1":{
        "scriptId":"u4"},
      "bb5fc219776241398ba91074f14ee50b":{
        "scriptId":"u5"},
      "81c1235877f9438b90a2592fa58a8e9d":{
        "scriptId":"u6"},
      "cf16f2e09e2d4035bc19c2135d37a1d0":{
        "scriptId":"u7"},
      "d8cf724cbd934951a4d73f1b37501249":{
        "scriptId":"u8"}},
    "8a77f53d8b4a427ca37c9ac28e4cb723":{
      "scriptId":"u9"},
    "7893aa998c19465294ccf1ac9dbc03c7":{
      "scriptId":"u10"},
    "aa4f19340201401ba3ccfca1b96e90d3":{
      "scriptId":"u11"},
    "6a52782d5c5a43578ebb4630ae1f1da0":{
      "scriptId":"u12"},
    "f4892cbdf32e46e18999e5ee29a3ed88":{
      "scriptId":"u13"},
    "95280eb6c20d4b1e8897a05458417593":{
      "scriptId":"u14"},
    "e2288d6a9cef4d38b6276f8c0c05fdcc":{
      "scriptId":"u15"},
    "45e124c998e64c249612d51dcf164bb8":{
      "scriptId":"u16"},
    "636f7d6fdf3d4d878543fd3c31e25f83":{
      "scriptId":"u17"},
    "651d49bbd2d14a729c23f78fbb2d8e72":{
      "scriptId":"u18"},
    "d86233ba748c4b21b359a78ec5a2f26f":{
      "scriptId":"u19"},
    "ce6e64d74f4d429d994d3ad7ff52597c":{
      "scriptId":"u20"},
    "c151c5321e664528bf58e4e7ee0b0323":{
      "scriptId":"u21"},
    "ce12f77ec1f64460aa3801670794ee90":{
      "scriptId":"u22"},
    "dbc117d9a32f4008969dfb66455a3635":{
      "scriptId":"u23"},
    "885e0fd9fe2d445fb42752c1dd953472":{
      "scriptId":"u24"},
    "ccd62a2408a0451c82debe39fb4eaa9e":{
      "scriptId":"u25"},
    "c4d31a05fdf141ae8cc20504a1581927":{
      "scriptId":"u26"},
    "7945509586f848d1876d67ea5579b760":{
      "scriptId":"u27"},
    "88e5fc5fa4854499ae95cfb1d467c469":{
      "scriptId":"u28"},
    "d7a9e715d1044f86bd38049ef42cc3e6":{
      "scriptId":"u29"},
    "626647c28dd04a7a87b12feb91577fa7":{
      "scriptId":"u30"},
    "b3c8c5b5a6a34d7e874442c715ae87d3":{
      "scriptId":"u31"},
    "ed047f9d6a1b4176a899a9a361fbb180":{
      "scriptId":"u32"},
    "87fed5770f72431fa0d29565281ab66e":{
      "scriptId":"u33"},
    "690415de3bac4ee78b52d73783324d04":{
      "scriptId":"u34"},
    "9d27d4dac9c64480b6628e25d576d2d3":{
      "scriptId":"u35"},
    "2debf5e416854209ad9f1dfc61a28893":{
      "scriptId":"u36"},
    "495840792abe4bfc8e4317f1efeb348b":{
      "scriptId":"u37"},
    "31300a90148a4d7cbb4d569ea7721d89":{
      "scriptId":"u38"},
    "985f8f90348d4941913dead9a90c76e9":{
      "scriptId":"u39"},
    "5b7ac762b20d4e24821522059377fb9f":{
      "scriptId":"u40"},
    "74e62e04a7be4ee381ff484751878b9e":{
      "scriptId":"u41"},
    "db4398fe026b4ceda6085bb65064d0a7":{
      "scriptId":"u42"},
    "6c9a91bc5b7f452ca9f76f374b3de5f9":{
      "scriptId":"u43"},
    "375ba7a0e41c41259249ea2d5e97c8c0":{
      "scriptId":"u44"},
    "e2a775d3360a402eba72725e5ed01b4a":{
      "scriptId":"u45"},
    "b2e67366fc8b4265a1cf0832768020b3":{
      "scriptId":"u46"},
    "eb59c429b0024fa4875457dff9cb87bf":{
      "scriptId":"u47"},
    "5e8386ecfdc74cf984f3de50d1e5f390":{
      "scriptId":"u48"},
    "0f5647afc6874166b89feb04aefa967f":{
      "scriptId":"u49"},
    "b1fd117c0a6e4bc3acf89a2175a035db":{
      "scriptId":"u50"},
    "88d0c84a17e845d19618be3e958f1693":{
      "scriptId":"u51"},
    "31321709edc24e9bb603ff316642e146":{
      "scriptId":"u52"},
    "f5dc5e5b96364a99a83d026e943038e5":{
      "scriptId":"u53"}}});