$axure.loadCurrentPage({
  "url":"e-mail.html",
  "generationDate":new Date(1415446119333.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5bbd738838da41e0bc6ded0cb9dfa47f",
    "type":"Axure:Page",
    "name":"E-mail",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a46ad020ca8e4f7b83baf1a2396835b3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"70880914498a4ae18e7e174f0301d35f"},
{
          "id":"36d58d467bf74cb09c8f946e152d1c1f",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'HelveticaNeue', 'Helvetica Neue'",
            "fontSize":"21px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":70,
              "y":145},
            "size":{
              "width":170,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d89451d822544bf1b2c142a86b91dd34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                "fontSize":"21px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":145},
                "size":{
                  "width":170,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "annotation":{
            "Description":"Indicate how many messages in a thread"},
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "70880914498a4ae18e7e174f0301d35f":{
      "packageId":"70880914498a4ae18e7e174f0301d35f",
      "type":"Axure:Master",
      "name":"E-mail",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9a095eb01a5d4f7689e840bdd23bca63",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800}},
            "adaptiveStyles":{
},
            "masterId":"a3c9ec5525e347978067bf5cebf60c89"},
{
            "id":"8056ca107ee64c4e8fc702e7e9f6d765",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":146},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"39f6e4e537a34748aba45751fbb8ace4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":38,
                    "y":146},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/link_email_with_cloud/u20.png"}},
{
            "id":"fcb9fd92413047c291d970b7fe7e8e44",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":38,
                "y":185},
              "size":{
                "width":38,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dde4e4b8e126474c92a2678881f58773",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":38,
                    "y":185},
                  "size":{
                    "width":38,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b35b6e1a8b0e47a7b46920553c0d2465",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":204},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"cd91da8134b046499b0a37f196dfbb66",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":86,
                "y":185},
              "size":{
                "width":170,
                "height":18},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23d6a4fb9a4e44dcb141107f0d24fc9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":86,
                    "y":185},
                  "size":{
                    "width":170,
                    "height":18},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contact in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contact.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "annotation":{
              "Description":"Contact name resolved via address book"},
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c555f9fecef24e23a6cbcf5d0061b668",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":38,
                "y":215},
              "size":{
                "width":20,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb9d7f42bf9047eba2ad38e13d638e7b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":38,
                    "y":215},
                  "size":{
                    "width":20,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6e91a2ca1ff24fcd9a5f07b5fdcf65db",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":233},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"0d606fffc8be4b9ea79b06ea76d66789",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":86,
                "y":215},
              "size":{
                "width":170,
                "height":18},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a0cf5ad947d44c81883f063a9a45051c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":86,
                    "y":215},
                  "size":{
                    "width":170,
                    "height":18},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contact in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contact.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"51262d5cc77145eab5bd0adf78f22604",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":278},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"1dbb8f2b3d824dbc86fa7f74595a3ff4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":38,
                "y":245},
              "size":{
                "width":170,
                "height":18},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b501e09047794f0698613e83e461c632",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":38,
                    "y":245},
                  "size":{
                    "width":170,
                    "height":18},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3c12daba46b34816a5f5fc0ac61be18b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":38,
                "y":266},
              "size":{
                "width":170,
                "height":14},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c02b1170f6b24f1089252480f0ca38f7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":38,
                    "y":266},
                  "size":{
                    "width":170,
                    "height":14},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "annotation":{
              "Description":"Dates formatted according to user locale settings"},
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"441ef5c086894a789f5dcb10691f4d51",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":38,
                "y":290},
              "size":{
                "width":302,
                "height":233},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"748fc22992e94536a3b7bdec760d8fd7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":38,
                    "y":290},
                  "size":{
                    "width":302,
                    "height":233},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dc978936b20b4148bf91e86323233336",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"24px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2087FC,
                "opacity":1},
              "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
              "location":{
                "x":310,
                "y":647},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8785069bc2be4a49bbb8067879b15f0c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"24px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2087FC,
                    "opacity":1},
                  "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
                  "location":{
                    "x":310,
                    "y":647},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open E-mail Favorites in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"e-mail_favorites.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"809c970ace27429392aab807d5f92b7a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"24px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2087FC,
                "opacity":1},
              "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
              "location":{
                "x":206,
                "y":647},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31b74ce8202947919a1caa94c5a2f171",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"24px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2087FC,
                    "opacity":1},
                  "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
                  "location":{
                    "x":206,
                    "y":647},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f11bd8b2fa0d40799c55ec7cc4a92ce6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":42,
                "y":530},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cadde15459ae4123915e2ab2f4ace319",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":42,
                    "y":530},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/e-mail/u33.png"}},
{
            "id":"a0c2e9227d444e79a6765fe8c95b2e9e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
              "location":{
                "x":76,
                "y":538},
              "size":{
                "width":104,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fdad826a19264738bcd80293b041a6fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
                  "location":{
                    "x":76,
                    "y":538},
                  "size":{
                    "width":104,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"91c0f0d773ea48e88478a63a91a9a59c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":192,
                "y":530},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7bc59e1c16647079164dd9f05e9492d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":192,
                    "y":530},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/e-mail/u33.png"}},
{
            "id":"b36adfbb32b5489b85c00c142c9316d3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
              "location":{
                "x":226,
                "y":538},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19ad90ac4cf84c829d2e8bc32ff862c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
                  "location":{
                    "x":226,
                    "y":538},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bac0d51f8f3248038b6e7cebeb0d455b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":42,
                "y":566},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7261ce632f0945b5b3de1c74100da69d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":42,
                    "y":566},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/e-mail/u33.png"}},
{
            "id":"c18e847cdea14623938fcf448091b732",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
              "location":{
                "x":76,
                "y":565},
              "size":{
                "width":269,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"03235b90401045f78324733f978c0e75",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
                  "location":{
                    "x":76,
                    "y":565},
                  "size":{
                    "width":269,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"79e9ac989ae64be9a8e9437eacc16ae1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"28px",
              "baseStyle":"fe2f353aa2c746628fee9754f4754197",
              "location":{
                "x":42,
                "y":648},
              "size":{
                "width":29,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97f9e2f59f1c45749e3d7b8d2140b13a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"28px",
                  "baseStyle":"fe2f353aa2c746628fee9754f4754197",
                  "location":{
                    "x":42,
                    "y":648},
                  "size":{
                    "width":29,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e4ba5663d68649449b3ab71f494eb361",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"28px",
              "baseStyle":"fe2f353aa2c746628fee9754f4754197",
              "location":{
                "x":96,
                "y":647},
              "size":{
                "width":29,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1b4fd0a0d8fc4547a41a05707b320a25",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"28px",
                  "baseStyle":"fe2f353aa2c746628fee9754f4754197",
                  "location":{
                    "x":96,
                    "y":647},
                  "size":{
                    "width":29,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4c7cccdf0e58459ba1fc99018f027a2a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":261,
                "y":650},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2d29ba5b195341fe9f34534e65464beb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":261,
                    "y":650},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Note in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"note.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/file_downloading/u27.png"}},
{
            "id":"6c4c19527ff14469bebb02a52a298ecd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"24px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2087FC,
                "opacity":1},
              "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
              "location":{
                "x":150,
                "y":649},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0d66ca15599548b694fe38da33430618",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"24px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2087FC,
                    "opacity":1},
                  "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
                  "location":{
                    "x":150,
                    "y":649},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Select Move target in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"select_move_target.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"edb2608367654745ac48cf9637158788",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":242,
                "y":154},
              "size":{
                "width":30,
                "height":6},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a3831ce0e31e42959f235b0ae00876db",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":242,
                    "y":154},
                  "size":{
                    "width":30,
                    "height":6},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/folder_content/u14.png"}},
{
            "id":"a7d97fd7c68940a79a06580fdcbc3334",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":286,
                "y":145},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7e4dade610b4f9db98547f2cf5160e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":286,
                    "y":145},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Image in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"image.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/file_downloading/u36.png"}},
{
            "id":"e1f00e507efd424eba60104decd3de64",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":318,
                "y":145},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9e6d7ceea0f14de28f45d46984804734",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":318,
                    "y":145},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/file_downloading/u38.png"}}]}},
    "a3c9ec5525e347978067bf5cebf60c89":{
      "packageId":"a3c9ec5525e347978067bf5cebf60c89",
      "type":"Axure:Master",
      "name":"EverDesk",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"12d11790695a4d9c8f38121434d74291",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc01043f76a74695a1cc1a0bab35dcd3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u1.png"}},
{
            "id":"9721dd10be0b4426b2d7c96348809de4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":32,
                "y":118},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a80150cd919b40c08ba799c9991e3be1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":32,
                    "y":118},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u3.png"}},
{
            "id":"bb5fc219776241398ba91074f14ee50b",
            "label":"text - h2",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"21px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":144,
                "y":130},
              "size":{
                "width":95,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81c1235877f9438b90a2592fa58a8e9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"21px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":144,
                    "y":130},
                  "size":{
                    "width":95,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cf16f2e09e2d4035bc19c2135d37a1d0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":37.5,
                "y":119},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8cf724cbd934951a4d73f1b37501249",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37.5,
                    "y":119},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u7.png"}}]}}},
  "objectPaths":{
    "a46ad020ca8e4f7b83baf1a2396835b3":{
      "scriptId":"u0",
      "9a095eb01a5d4f7689e840bdd23bca63":{
        "scriptId":"u1",
        "12d11790695a4d9c8f38121434d74291":{
          "scriptId":"u2"},
        "dc01043f76a74695a1cc1a0bab35dcd3":{
          "scriptId":"u3"},
        "9721dd10be0b4426b2d7c96348809de4":{
          "scriptId":"u4"},
        "a80150cd919b40c08ba799c9991e3be1":{
          "scriptId":"u5"},
        "bb5fc219776241398ba91074f14ee50b":{
          "scriptId":"u6"},
        "81c1235877f9438b90a2592fa58a8e9d":{
          "scriptId":"u7"},
        "cf16f2e09e2d4035bc19c2135d37a1d0":{
          "scriptId":"u8"},
        "d8cf724cbd934951a4d73f1b37501249":{
          "scriptId":"u9"}},
      "8056ca107ee64c4e8fc702e7e9f6d765":{
        "scriptId":"u10"},
      "39f6e4e537a34748aba45751fbb8ace4":{
        "scriptId":"u11"},
      "fcb9fd92413047c291d970b7fe7e8e44":{
        "scriptId":"u12"},
      "dde4e4b8e126474c92a2678881f58773":{
        "scriptId":"u13"},
      "b35b6e1a8b0e47a7b46920553c0d2465":{
        "scriptId":"u14"},
      "cd91da8134b046499b0a37f196dfbb66":{
        "scriptId":"u15"},
      "23d6a4fb9a4e44dcb141107f0d24fc9d":{
        "scriptId":"u16"},
      "c555f9fecef24e23a6cbcf5d0061b668":{
        "scriptId":"u17"},
      "bb9d7f42bf9047eba2ad38e13d638e7b":{
        "scriptId":"u18"},
      "6e91a2ca1ff24fcd9a5f07b5fdcf65db":{
        "scriptId":"u19"},
      "0d606fffc8be4b9ea79b06ea76d66789":{
        "scriptId":"u20"},
      "a0cf5ad947d44c81883f063a9a45051c":{
        "scriptId":"u21"},
      "51262d5cc77145eab5bd0adf78f22604":{
        "scriptId":"u22"},
      "1dbb8f2b3d824dbc86fa7f74595a3ff4":{
        "scriptId":"u23"},
      "b501e09047794f0698613e83e461c632":{
        "scriptId":"u24"},
      "3c12daba46b34816a5f5fc0ac61be18b":{
        "scriptId":"u25"},
      "c02b1170f6b24f1089252480f0ca38f7":{
        "scriptId":"u26"},
      "441ef5c086894a789f5dcb10691f4d51":{
        "scriptId":"u27"},
      "748fc22992e94536a3b7bdec760d8fd7":{
        "scriptId":"u28"},
      "dc978936b20b4148bf91e86323233336":{
        "scriptId":"u29"},
      "8785069bc2be4a49bbb8067879b15f0c":{
        "scriptId":"u30"},
      "809c970ace27429392aab807d5f92b7a":{
        "scriptId":"u31"},
      "31b74ce8202947919a1caa94c5a2f171":{
        "scriptId":"u32"},
      "f11bd8b2fa0d40799c55ec7cc4a92ce6":{
        "scriptId":"u33"},
      "cadde15459ae4123915e2ab2f4ace319":{
        "scriptId":"u34"},
      "a0c2e9227d444e79a6765fe8c95b2e9e":{
        "scriptId":"u35"},
      "fdad826a19264738bcd80293b041a6fa":{
        "scriptId":"u36"},
      "91c0f0d773ea48e88478a63a91a9a59c":{
        "scriptId":"u37"},
      "c7bc59e1c16647079164dd9f05e9492d":{
        "scriptId":"u38"},
      "b36adfbb32b5489b85c00c142c9316d3":{
        "scriptId":"u39"},
      "19ad90ac4cf84c829d2e8bc32ff862c7":{
        "scriptId":"u40"},
      "bac0d51f8f3248038b6e7cebeb0d455b":{
        "scriptId":"u41"},
      "7261ce632f0945b5b3de1c74100da69d":{
        "scriptId":"u42"},
      "c18e847cdea14623938fcf448091b732":{
        "scriptId":"u43"},
      "03235b90401045f78324733f978c0e75":{
        "scriptId":"u44"},
      "79e9ac989ae64be9a8e9437eacc16ae1":{
        "scriptId":"u45"},
      "97f9e2f59f1c45749e3d7b8d2140b13a":{
        "scriptId":"u46"},
      "e4ba5663d68649449b3ab71f494eb361":{
        "scriptId":"u47"},
      "1b4fd0a0d8fc4547a41a05707b320a25":{
        "scriptId":"u48"},
      "4c7cccdf0e58459ba1fc99018f027a2a":{
        "scriptId":"u49"},
      "2d29ba5b195341fe9f34534e65464beb":{
        "scriptId":"u50"},
      "6c4c19527ff14469bebb02a52a298ecd":{
        "scriptId":"u51"},
      "0d66ca15599548b694fe38da33430618":{
        "scriptId":"u52"},
      "edb2608367654745ac48cf9637158788":{
        "scriptId":"u53"},
      "a3831ce0e31e42959f235b0ae00876db":{
        "scriptId":"u54"},
      "a7d97fd7c68940a79a06580fdcbc3334":{
        "scriptId":"u55"},
      "d7e4dade610b4f9db98547f2cf5160e9":{
        "scriptId":"u56"},
      "e1f00e507efd424eba60104decd3de64":{
        "scriptId":"u57"},
      "9e6d7ceea0f14de28f45d46984804734":{
        "scriptId":"u58"}},
    "36d58d467bf74cb09c8f946e152d1c1f":{
      "scriptId":"u59"},
    "d89451d822544bf1b2c142a86b91dd34":{
      "scriptId":"u60"}}});