$axure.loadCurrentPage({
  "url":"folder_mass_actions.html",
  "generationDate":new Date(1415446117135.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3bf3985bec8e452f88f551dfa83439d1",
    "type":"Axure:Page",
    "name":"Folder Mass Actions",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8e1d92f85301477db82f4cc554a55796",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fab5eb8bf7aa448d8f56cd2dd7226adb"}]}},
  "masters":{
    "fab5eb8bf7aa448d8f56cd2dd7226adb":{
      "packageId":"fab5eb8bf7aa448d8f56cd2dd7226adb",
      "type":"Axure:Master",
      "name":"Folder Mass Actions",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"dc53bb3bcf5e479db3290d85fa582bf5",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800}},
            "adaptiveStyles":{
},
            "masterId":"a3c9ec5525e347978067bf5cebf60c89"},
{
            "id":"43a85497c0a24b249e399c911991916c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":44,
                "y":144},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"786bbf3579484c87b92dac970f6450d8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":44,
                    "y":144},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Root folder with content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"root_folder_with_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/link_email_with_cloud/u20.png"}},
{
            "id":"39b1b73ee6f44a7dbdb5a53c2ecaff81",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":316,
                "y":152},
              "size":{
                "width":30,
                "height":6},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ddad65ba0c5d403bbc82c0df9882256c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":316,
                    "y":152},
                  "size":{
                    "width":30,
                    "height":6},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/folder_content/u14.png"}},
{
            "id":"e50adbb2116c4e8a935a5a07969a7e24",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":78,
                "y":228},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b7b076d3b6a1448f82f72b0e81b29499",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":78,
                    "y":228},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"cae0229710fd4ef9b7ec41297c6a8152",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":118,
                "y":235},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99c73c5414da4789a4c610853374babc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":118,
                    "y":235},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"63a0b12ac266435eb81b383b4960605b",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":264},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"125129c11fbf4776a2ce2ee27010a866",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":78,
                "y":274},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9a8dc26cd77c42788ff94106e7208b57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":78,
                    "y":274},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"c9af9f4ad8c844da88b40ade012429c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":118,
                "y":281},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93bfcb13f208420f87a4a115199bc399",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":118,
                    "y":281},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"54c17eaf3f7c4cb187c837013425c8d3",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":307},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"99e87aa6be8d4b8f8706632ccf4b74b0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":78,
                "y":317},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0144238dabf44dbfadfdbf4ab5e0cebd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":78,
                    "y":317},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"11e327335d6e4fd2886611ddb4a4f93f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":118,
                "y":324},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c1cdbcfa3e940b3bdf52da857458a7d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":118,
                    "y":324},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"916a5dfeb0ef40358372b9f4ef295b03",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":350},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"9bb66819467d449fa0a6c674bde2a22b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE9E9E9},
              "location":{
                "x":32,
                "y":357},
              "size":{
                "width":318,
                "height":22},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b657303d3d89483e8fb1ae7bd495fd31",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE9E9E9},
                  "location":{
                    "x":32,
                    "y":357},
                  "size":{
                    "width":318,
                    "height":22},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/imap_pop3/u36.png"}},
{
            "id":"8d211ab770784a49887810f66bc1459c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":48,
                "y":360},
              "size":{
                "width":29,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"909626e158374309bbae7b9580b13fdb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":48,
                    "y":360},
                  "size":{
                    "width":29,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"853b169de865409cbff33c812cbe31fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":78,
                "y":384},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67416fe647ca482281ea4816b7fa9397",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":78,
                    "y":384},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"de7286f7178e43549ba4c9572976f333",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":118,
                "y":391},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"36cc961e01c743e68af404cea44a57aa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":118,
                    "y":391},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"79d25a938978435b888e43b77695580a",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":414},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"057be8b474a34cb59cacac82c9b22d00",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":78,
                "y":424},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c6cff351e05640d09e02e188c9cc2c65",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":78,
                    "y":424},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"80c81574ec41482f965577bb24071db2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":118,
                "y":431},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9b109eb4e7d74cec8a2b10980555c08f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":118,
                    "y":431},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d5d62b353b75420ab904f4688c08f903",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":457},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"75e3c3f592364cda90012d6d53513793",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":78,
                "y":467},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5f38ac6d9e7b4aecb23a21b5a6e9ae5c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":78,
                    "y":467},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"b185e9bcb7b54225a1a887613c805663",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":118,
                "y":474},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7aa7edfb7b084878983868edd2c2f863",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":118,
                    "y":474},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3e19125dd6d94c1184960a89914c7c12",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":500},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"e9a3ba96f1c046b4ae0baffe4af7b30e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":78,
                "y":188},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9d97e54f87d848409f138c5dc60439f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":78,
                    "y":188},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"14c4d658c1114959a26b2c863726de8c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":118,
                "y":195},
              "size":{
                "width":168,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"85aa7b4c7c424c6281c47965189037a3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":118,
                    "y":195},
                  "size":{
                    "width":168,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a68721d58e3f445c931aa6eb50a781b1",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":218},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"6a0af3c90bd24353a76385cf01a61f4d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":43,
                "y":190},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3510aec72ef84518bf5cf82fc3d162d4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":43,
                    "y":190},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/folder_mass_actions/u53.png"}},
{
            "id":"e55da156a5d641f790b7548edff89381",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":43,
                "y":230},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b0acbc7d58e94b62abeea56b82b738be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":43,
                    "y":230},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/folder_mass_actions/u55.png"}},
{
            "id":"9b51ede3d58d4f64a2ac695796fe5649",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":43,
                "y":279},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a94f9401ff1f45a19b51b6961c057d2c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":43,
                    "y":279},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/folder_mass_actions/u55.png"}},
{
            "id":"66d74641c70449fe89439481a22d720c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":44,
                "y":387},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ea2a271d80be4f6fa54d40f3858dc2b0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":44,
                    "y":387},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/folder_mass_actions/u53.png"}},
{
            "id":"c2109e464ef9410cb4d2bec90b69a9cc",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":43,
                "y":429},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8574f242508340008f10ae14b05f4ccb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":43,
                    "y":429},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/folder_mass_actions/u53.png"}},
{
            "id":"8e58d0b3de254aae8910faca6110888d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":43,
                "y":470},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c0cde43701a94eca9e3acc479c18536d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":43,
                    "y":470},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/folder_mass_actions/u55.png"}},
{
            "id":"448fc656e64b413ab22deec308dae6b3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":43,
                "y":320},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"85eff0ce73e44cb7b59d5695974f6972",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":43,
                    "y":320},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/folder_mass_actions/u53.png"}},
{
            "id":"fbb18464d8de435fbca49a902cc7f3cb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"24px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2087FC,
                "opacity":1},
              "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
              "location":{
                "x":90,
                "y":142},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bd2e810d1f7e4c51bd99b60a682b9f3a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"24px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2087FC,
                    "opacity":1},
                  "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
                  "location":{
                    "x":90,
                    "y":142},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Select Copy target in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"select_copy_target.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"43f2af236ad14b47ae72e49a1b8c3b3f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"24px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2087FC,
                "opacity":1},
              "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
              "location":{
                "x":218,
                "y":142},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e061e387354241f8afa7d182ac1f48c0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"24px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2087FC,
                    "opacity":1},
                  "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
                  "location":{
                    "x":218,
                    "y":142},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a88c6b562d2d43ff8ef88f3f0f14b622",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"24px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2087FC,
                "opacity":1},
              "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
              "location":{
                "x":261,
                "y":142},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"292355cd04f241a388d7ff2ce5eaeb27",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"24px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2087FC,
                    "opacity":1},
                  "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
                  "location":{
                    "x":261,
                    "y":142},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2fa5c68402f1413cbdd992ad80ac3cd0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"24px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2087FC,
                "opacity":1},
              "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
              "location":{
                "x":133,
                "y":143},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dcc2b5fbb89841c494ecb57a8e972bd1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"24px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2087FC,
                    "opacity":1},
                  "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
                  "location":{
                    "x":133,
                    "y":143},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Select Move target in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"select_move_target.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8b2f3ed883a747859d42e37f5e2fe4aa",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'FontAwesome', 'FontAwesome'",
              "fontSize":"24px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2087FC,
                "opacity":1},
              "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
              "location":{
                "x":176,
                "y":141},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7318a2aabca74581aabe46442419af3a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'FontAwesome', 'FontAwesome'",
                  "fontSize":"24px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2087FC,
                    "opacity":1},
                  "baseStyle":"6e8405aad31a4b82bcba4963df950a97",
                  "location":{
                    "x":176,
                    "y":141},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder Mass Delete in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_mass_delete.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"07b5d17e830a41c1a952350847d75c8a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":32,
                "y":635},
              "size":{
                "width":320,
                "height":51},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee08233cf91a46ddb3c42e4bc6b84311",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":32,
                    "y":635},
                  "size":{
                    "width":320,
                    "height":51},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u13.png"}},
{
            "id":"d1b35909a11c4355884cf61a5e028d9c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":175,
                "y":639},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ead00c3ed8e54e02bd99a83c52e42ed6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":175,
                    "y":639},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"0682145b78104c7ea5b2109183843fe1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF4478FB,
                "opacity":1},
              "location":{
                "x":154,
                "y":671},
              "size":{
                "width":73,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4255aac72c534973aa04164b7f20d445",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF4478FB,
                    "opacity":1},
                  "location":{
                    "x":154,
                    "y":671},
                  "size":{
                    "width":73,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5d1cbd37790249bd8faf19a71b88daa1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":57,
                "y":639},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"301374e3ad8d4247b02be82f973e416c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":57,
                    "y":639},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"62cfe98e23c64514bed6a818dae0fa22",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":43,
                "y":671},
              "size":{
                "width":58,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f81b1b1c249b4a12be38532cca5e1575",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":43,
                    "y":671},
                  "size":{
                    "width":58,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b0f9e7d42f234602a748b4485f4d43a5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":302,
                "y":639},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a989a00c911d484b9385083ebb327949",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":302,
                    "y":639},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"e94b23692ab94442bc5f41781d039233",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":294,
                "y":671},
              "size":{
                "width":45,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e6176b70cace458fb58781a3be4bb1f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":294,
                    "y":671},
                  "size":{
                    "width":45,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "a3c9ec5525e347978067bf5cebf60c89":{
      "packageId":"a3c9ec5525e347978067bf5cebf60c89",
      "type":"Axure:Master",
      "name":"EverDesk",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"12d11790695a4d9c8f38121434d74291",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc01043f76a74695a1cc1a0bab35dcd3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u1.png"}},
{
            "id":"9721dd10be0b4426b2d7c96348809de4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":32,
                "y":118},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a80150cd919b40c08ba799c9991e3be1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":32,
                    "y":118},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u3.png"}},
{
            "id":"bb5fc219776241398ba91074f14ee50b",
            "label":"text - h2",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"21px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":144,
                "y":130},
              "size":{
                "width":95,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81c1235877f9438b90a2592fa58a8e9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"21px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":144,
                    "y":130},
                  "size":{
                    "width":95,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cf16f2e09e2d4035bc19c2135d37a1d0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":37.5,
                "y":119},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8cf724cbd934951a4d73f1b37501249",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37.5,
                    "y":119},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u7.png"}}]}}},
  "objectPaths":{
    "8e1d92f85301477db82f4cc554a55796":{
      "scriptId":"u0",
      "dc53bb3bcf5e479db3290d85fa582bf5":{
        "scriptId":"u1",
        "12d11790695a4d9c8f38121434d74291":{
          "scriptId":"u2"},
        "dc01043f76a74695a1cc1a0bab35dcd3":{
          "scriptId":"u3"},
        "9721dd10be0b4426b2d7c96348809de4":{
          "scriptId":"u4"},
        "a80150cd919b40c08ba799c9991e3be1":{
          "scriptId":"u5"},
        "bb5fc219776241398ba91074f14ee50b":{
          "scriptId":"u6"},
        "81c1235877f9438b90a2592fa58a8e9d":{
          "scriptId":"u7"},
        "cf16f2e09e2d4035bc19c2135d37a1d0":{
          "scriptId":"u8"},
        "d8cf724cbd934951a4d73f1b37501249":{
          "scriptId":"u9"}},
      "43a85497c0a24b249e399c911991916c":{
        "scriptId":"u10"},
      "786bbf3579484c87b92dac970f6450d8":{
        "scriptId":"u11"},
      "39b1b73ee6f44a7dbdb5a53c2ecaff81":{
        "scriptId":"u12"},
      "ddad65ba0c5d403bbc82c0df9882256c":{
        "scriptId":"u13"},
      "e50adbb2116c4e8a935a5a07969a7e24":{
        "scriptId":"u14"},
      "b7b076d3b6a1448f82f72b0e81b29499":{
        "scriptId":"u15"},
      "cae0229710fd4ef9b7ec41297c6a8152":{
        "scriptId":"u16"},
      "99c73c5414da4789a4c610853374babc":{
        "scriptId":"u17"},
      "63a0b12ac266435eb81b383b4960605b":{
        "scriptId":"u18"},
      "125129c11fbf4776a2ce2ee27010a866":{
        "scriptId":"u19"},
      "9a8dc26cd77c42788ff94106e7208b57":{
        "scriptId":"u20"},
      "c9af9f4ad8c844da88b40ade012429c2":{
        "scriptId":"u21"},
      "93bfcb13f208420f87a4a115199bc399":{
        "scriptId":"u22"},
      "54c17eaf3f7c4cb187c837013425c8d3":{
        "scriptId":"u23"},
      "99e87aa6be8d4b8f8706632ccf4b74b0":{
        "scriptId":"u24"},
      "0144238dabf44dbfadfdbf4ab5e0cebd":{
        "scriptId":"u25"},
      "11e327335d6e4fd2886611ddb4a4f93f":{
        "scriptId":"u26"},
      "0c1cdbcfa3e940b3bdf52da857458a7d":{
        "scriptId":"u27"},
      "916a5dfeb0ef40358372b9f4ef295b03":{
        "scriptId":"u28"},
      "9bb66819467d449fa0a6c674bde2a22b":{
        "scriptId":"u29"},
      "b657303d3d89483e8fb1ae7bd495fd31":{
        "scriptId":"u30"},
      "8d211ab770784a49887810f66bc1459c":{
        "scriptId":"u31"},
      "909626e158374309bbae7b9580b13fdb":{
        "scriptId":"u32"},
      "853b169de865409cbff33c812cbe31fd":{
        "scriptId":"u33"},
      "67416fe647ca482281ea4816b7fa9397":{
        "scriptId":"u34"},
      "de7286f7178e43549ba4c9572976f333":{
        "scriptId":"u35"},
      "36cc961e01c743e68af404cea44a57aa":{
        "scriptId":"u36"},
      "79d25a938978435b888e43b77695580a":{
        "scriptId":"u37"},
      "057be8b474a34cb59cacac82c9b22d00":{
        "scriptId":"u38"},
      "c6cff351e05640d09e02e188c9cc2c65":{
        "scriptId":"u39"},
      "80c81574ec41482f965577bb24071db2":{
        "scriptId":"u40"},
      "9b109eb4e7d74cec8a2b10980555c08f":{
        "scriptId":"u41"},
      "d5d62b353b75420ab904f4688c08f903":{
        "scriptId":"u42"},
      "75e3c3f592364cda90012d6d53513793":{
        "scriptId":"u43"},
      "5f38ac6d9e7b4aecb23a21b5a6e9ae5c":{
        "scriptId":"u44"},
      "b185e9bcb7b54225a1a887613c805663":{
        "scriptId":"u45"},
      "7aa7edfb7b084878983868edd2c2f863":{
        "scriptId":"u46"},
      "3e19125dd6d94c1184960a89914c7c12":{
        "scriptId":"u47"},
      "e9a3ba96f1c046b4ae0baffe4af7b30e":{
        "scriptId":"u48"},
      "9d97e54f87d848409f138c5dc60439f9":{
        "scriptId":"u49"},
      "14c4d658c1114959a26b2c863726de8c":{
        "scriptId":"u50"},
      "85aa7b4c7c424c6281c47965189037a3":{
        "scriptId":"u51"},
      "a68721d58e3f445c931aa6eb50a781b1":{
        "scriptId":"u52"},
      "6a0af3c90bd24353a76385cf01a61f4d":{
        "scriptId":"u53"},
      "3510aec72ef84518bf5cf82fc3d162d4":{
        "scriptId":"u54"},
      "e55da156a5d641f790b7548edff89381":{
        "scriptId":"u55"},
      "b0acbc7d58e94b62abeea56b82b738be":{
        "scriptId":"u56"},
      "9b51ede3d58d4f64a2ac695796fe5649":{
        "scriptId":"u57"},
      "a94f9401ff1f45a19b51b6961c057d2c":{
        "scriptId":"u58"},
      "66d74641c70449fe89439481a22d720c":{
        "scriptId":"u59"},
      "ea2a271d80be4f6fa54d40f3858dc2b0":{
        "scriptId":"u60"},
      "c2109e464ef9410cb4d2bec90b69a9cc":{
        "scriptId":"u61"},
      "8574f242508340008f10ae14b05f4ccb":{
        "scriptId":"u62"},
      "8e58d0b3de254aae8910faca6110888d":{
        "scriptId":"u63"},
      "c0cde43701a94eca9e3acc479c18536d":{
        "scriptId":"u64"},
      "448fc656e64b413ab22deec308dae6b3":{
        "scriptId":"u65"},
      "85eff0ce73e44cb7b59d5695974f6972":{
        "scriptId":"u66"},
      "fbb18464d8de435fbca49a902cc7f3cb":{
        "scriptId":"u67"},
      "bd2e810d1f7e4c51bd99b60a682b9f3a":{
        "scriptId":"u68"},
      "43f2af236ad14b47ae72e49a1b8c3b3f":{
        "scriptId":"u69"},
      "e061e387354241f8afa7d182ac1f48c0":{
        "scriptId":"u70"},
      "a88c6b562d2d43ff8ef88f3f0f14b622":{
        "scriptId":"u71"},
      "292355cd04f241a388d7ff2ce5eaeb27":{
        "scriptId":"u72"},
      "2fa5c68402f1413cbdd992ad80ac3cd0":{
        "scriptId":"u73"},
      "dcc2b5fbb89841c494ecb57a8e972bd1":{
        "scriptId":"u74"},
      "8b2f3ed883a747859d42e37f5e2fe4aa":{
        "scriptId":"u75"},
      "7318a2aabca74581aabe46442419af3a":{
        "scriptId":"u76"},
      "07b5d17e830a41c1a952350847d75c8a":{
        "scriptId":"u77"},
      "ee08233cf91a46ddb3c42e4bc6b84311":{
        "scriptId":"u78"},
      "d1b35909a11c4355884cf61a5e028d9c":{
        "scriptId":"u79"},
      "ead00c3ed8e54e02bd99a83c52e42ed6":{
        "scriptId":"u80"},
      "0682145b78104c7ea5b2109183843fe1":{
        "scriptId":"u81"},
      "4255aac72c534973aa04164b7f20d445":{
        "scriptId":"u82"},
      "5d1cbd37790249bd8faf19a71b88daa1":{
        "scriptId":"u83"},
      "301374e3ad8d4247b02be82f973e416c":{
        "scriptId":"u84"},
      "62cfe98e23c64514bed6a818dae0fa22":{
        "scriptId":"u85"},
      "f81b1b1c249b4a12be38532cca5e1575":{
        "scriptId":"u86"},
      "b0f9e7d42f234602a748b4485f4d43a5":{
        "scriptId":"u87"},
      "a989a00c911d484b9385083ebb327949":{
        "scriptId":"u88"},
      "e94b23692ab94442bc5f41781d039233":{
        "scriptId":"u89"},
      "e6176b70cace458fb58781a3be4bb1f3":{
        "scriptId":"u90"}}}});