$axure.loadCurrentPage({
  "url":"favorites.html",
  "generationDate":new Date(1415446119932.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"87672fc610a34ca6af6039f4a738f5fa",
    "type":"Axure:Page",
    "name":"Favorites",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"34cfb5ed94904b33bb1ba0947c8416d4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a3c9ec5525e347978067bf5cebf60c89"},
{
          "id":"c6091bcf6d7c4ddab1cea2d107ab5a28",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":636}},
          "adaptiveStyles":{
},
          "masterId":"d89314f89a58461fa7ad6fe92cbb66a9"},
{
          "id":"7d20cd49ba9b455c89f135d7fcded0f8",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'HelveticaNeue', 'Helvetica Neue'",
            "fontSize":"21px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":105,
              "y":144},
            "size":{
              "width":170,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4064df8c326447efa8cd04ef7398d794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                "fontSize":"21px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":105,
                  "y":144},
                "size":{
                  "width":170,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07120830db1d4ebd948a20179d090b55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":153.5},
            "size":{
              "width":30,
              "height":6},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a7cbbab4eb64fa7b54bc2a3c7b6b810",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":153.5},
                "size":{
                  "width":30,
                  "height":6},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/folder_content/u14.png"}},
{
          "id":"b363d1dcd52a4ac49b7582c56cd98152",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":181}},
          "adaptiveStyles":{
},
          "masterId":"b6a6a21b6e8345489b1ff49c557b5354"},
{
          "id":"b9d20eb24e5746e6bebe4b4a2d802c13",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":186},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de5c963c07b0460caa3fdfa34aa6ca79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":186},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/root_folder_with_content/u27.png"}},
{
          "id":"b98ce45a8a4844a382b9177227efbf9e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":229},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06a1d00ca7214c428aaa8e07a66e6aa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":229},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/root_folder_with_content/u27.png"}},
{
          "id":"34c44082f7024d9ebcffd2d33ba355e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":275},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08317e7d3a014b378a646d105c4d2e64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":275},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/root_folder_with_content/u27.png"}},
{
          "id":"7136eb51ec524896b72fdd7174e8a5a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":321},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8aabe29714e436bb5dc5206517dd7ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":321},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/root_folder_with_content/u27.png"}},
{
          "id":"861a7f79d54941b3947c4e0b544ee5c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":385},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f503b47a615549339d88e35f8563785a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":385},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/root_folder_with_content/u27.png"}},
{
          "id":"dfea0f93aeb94ac992deb19c22e2f0a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":428},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03392466eec9407fbf48b259743fbef1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":428},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/root_folder_with_content/u27.png"}},
{
          "id":"7758c7be9a304bce8f6406664bcb5769",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":471},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2921402605fa45318f0f5dcb220a5a7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":471},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/root_folder_with_content/u27.png"}},
{
          "id":"1414f862ba6043e9a7a033f037e7e059",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":179},
            "size":{
              "width":319,
              "height":39},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"748517f14f1942f5be9187d30784a68c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":179},
                "size":{
                  "width":319,
                  "height":39},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/favorites/u84.png"}},
{
          "id":"102230b8c5c2432f8ab048a64d1e4a22",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0033FF},
{
                  "color":0xFF0033FF},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":140,
              "y":195},
            "size":{
              "width":100,
              "height":7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efa2feafe585484cb7588e9a41855397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0033FF},
{
                      "color":0xFF0033FF},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":140,
                  "y":195},
                "size":{
                  "width":100,
                  "height":7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/file_downloading/u29.png"}},
{
          "id":"5c7ae99e43b94a7d8cd5261fce002a84",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
            "location":{
              "x":140,
              "y":195},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/file_downloading/u31_line.png"}},
{
          "id":"a5558cab979947beb39c2fb6231747cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
            "location":{
              "x":48,
              "y":189},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1b8e377b98a409d83650d1ee9aeeba4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"ab5c2c1a2b9f43808148be3cd9a3fe1f",
                "location":{
                  "x":48,
                  "y":189},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "a3c9ec5525e347978067bf5cebf60c89":{
      "packageId":"a3c9ec5525e347978067bf5cebf60c89",
      "type":"Axure:Master",
      "name":"EverDesk",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"12d11790695a4d9c8f38121434d74291",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc01043f76a74695a1cc1a0bab35dcd3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u1.png"}},
{
            "id":"9721dd10be0b4426b2d7c96348809de4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":32,
                "y":118},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a80150cd919b40c08ba799c9991e3be1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":32,
                    "y":118},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u3.png"}},
{
            "id":"bb5fc219776241398ba91074f14ee50b",
            "label":"text - h2",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"21px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":144,
                "y":130},
              "size":{
                "width":95,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81c1235877f9438b90a2592fa58a8e9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"21px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":144,
                    "y":130},
                  "size":{
                    "width":95,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cf16f2e09e2d4035bc19c2135d37a1d0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":37.5,
                "y":119},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8cf724cbd934951a4d73f1b37501249",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37.5,
                    "y":119},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u7.png"}}]}},
    "d89314f89a58461fa7ad6fe92cbb66a9":{
      "packageId":"d89314f89a58461fa7ad6fe92cbb66a9",
      "type":"Axure:Master",
      "name":"Tabbar",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"49ed5d571ebc47deb5cebc13c668cf56",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":51},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee972d7e6bce42a7be40a4cec819d967",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":51},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u13.png"}},
{
            "id":"5e1f04ce81654c5499486eefac74ea97",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":143,
                "y":4},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0e0bddaa66bf446ea4e833d29316d0e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":143,
                    "y":4},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Root folder with content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"root_folder_with_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"67a5021058454d6a839becccbdc39e43",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF4478FB,
                "opacity":1},
              "location":{
                "x":122,
                "y":36},
              "size":{
                "width":73,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9e38759bdf44e298e31bf83cca565a1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF4478FB,
                    "opacity":1},
                  "location":{
                    "x":122,
                    "y":36},
                  "size":{
                    "width":73,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0993f26346014d4bb26856d5e5d1db8d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":25,
                "y":4},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"066c9b84b33240389b02efaced716c90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":25,
                    "y":4},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Favorites in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"favorites.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"760cf6f4d7e14daeacd018ba740d47bb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":11,
                "y":36},
              "size":{
                "width":58,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9766b0c194e4a29a9492e090163ebc9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":11,
                    "y":36},
                  "size":{
                    "width":58,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"655d64d13b9e426fac601ad145b3f715",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":270,
                "y":4},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7d931fa140ed4a7796b1f5c6b18b54a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":270,
                    "y":4},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"af93c72b1694414587a00604ec54d3dd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":262,
                "y":36},
              "size":{
                "width":45,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dffe95781d8b4c599a60053760cdfe99",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":262,
                    "y":36},
                  "size":{
                    "width":45,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "b6a6a21b6e8345489b1ff49c557b5354":{
      "packageId":"b6a6a21b6e8345489b1ff49c557b5354",
      "type":"Axure:Master",
      "name":"Folder Table",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"edfc2f4ce39745e1bf776d40ceea8f59",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":46},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dcc53fc4119c489ba4c4387a5ce5891d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":46},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"d8ebf613679243f98e5e301233784516",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":53},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"32ce2f1906d844189558c2f8a34fe123",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":53},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9affdfe40f654aa397ff2597ae37939b",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":79},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"c1ff910c9c7348fba65de05303d26a24",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":89},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4fbc2d421ba1461dbe178b75808824c2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":89},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"fbd97f546dc54b009c185aa832f6466a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":96},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d42d5d8bb2224092a300e745105c635d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":96},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9f14d206462e48b9b40bab12bba2d31d",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":122},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"d085552437cb4a2097533f961c404969",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":132},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e7346c892eb49b68ad04ac33e1f7f1d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":132},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"86b2d89a36f844a38dd221378968b405",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":139},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"28776cc25a17427b95cd43b610efee10",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":139},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7ea28152c03941299e4f169d094ebd59",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":165},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"eacf152fe7754c0d9e032fb59580759a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE9E9E9},
              "location":{
                "x":0,
                "y":172},
              "size":{
                "width":318,
                "height":22},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"62e224545cd44e458675e6da3eaa401b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE9E9E9},
                  "location":{
                    "x":0,
                    "y":172},
                  "size":{
                    "width":318,
                    "height":22},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/imap_pop3/u36.png"}},
{
            "id":"5124ca61545c4c17b645962eaaca0a46",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":16,
                "y":175},
              "size":{
                "width":29,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9245ee5ad6e4a31bd45ffd7a8579ee8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":16,
                    "y":175},
                  "size":{
                    "width":29,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3dc96932814c4e3bb92028225f4c9569",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":196},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfe85946c4db4df29374b8393d5e1ade",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":196},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"85b8630675134bc8b54e71921db21891",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":203},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0e15ad3662b14c369cdbac7ef4e96e5d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":203},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open File Downloading in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"file_downloading.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cbd8267cf4044508b19c8b2ad0c72e9a",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":229},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"39ea4dbb62c847e7816e41fa39a663f8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":239},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1eae7af5be7d42278105e53ad6180c5c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":239},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"09df8f3ac6344f6782c35cdd4e133340",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":246},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d985f851eead4807900589566e27ebee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":246},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Image in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"image.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8b2275de79fe4c27aba0ba15fa76752a",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":272},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"4355a551ad1b4242a44a2412753f8dc6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":282},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31dc927d10a74775bc9034e48c217a52",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":282},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"26aa636b545c4947ae36bf3df06893fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":282},
              "size":{
                "width":171,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0cac14fb90ee449bbfa615b84da9d38c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":282},
                  "size":{
                    "width":171,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open E-mail in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"e-mail.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ea4f935cf86b4c24a908c261333b946c",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":315},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"3c79410579c2493eb7cbedd74d84920f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":0},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7902d20f41f740a487e03bac900c7603",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":0},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/first_launch/u15.png"}},
{
            "id":"e5d19c2b92ec4c9789da2cea3a74fe91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":7},
              "size":{
                "width":260,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a47e22c85df346839de86e05679962ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":7},
                  "size":{
                    "width":260,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Folder content in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"folder_content.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7d1c2fea52054efea49aef8961aef751",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":33},
              "size":{
                "width":312,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/add_cloud_account/u16_line.png"}},
{
            "id":"4877d59f4c7b44c2bb6800ab1b3df9b2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":49,
                "y":301},
              "size":{
                "width":251,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d49a78d46e25494a900cb6d5274956cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":301},
                  "size":{
                    "width":251,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open E-mail in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"e-mail.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "34cfb5ed94904b33bb1ba0947c8416d4":{
      "scriptId":"u0",
      "12d11790695a4d9c8f38121434d74291":{
        "scriptId":"u1"},
      "dc01043f76a74695a1cc1a0bab35dcd3":{
        "scriptId":"u2"},
      "9721dd10be0b4426b2d7c96348809de4":{
        "scriptId":"u3"},
      "a80150cd919b40c08ba799c9991e3be1":{
        "scriptId":"u4"},
      "bb5fc219776241398ba91074f14ee50b":{
        "scriptId":"u5"},
      "81c1235877f9438b90a2592fa58a8e9d":{
        "scriptId":"u6"},
      "cf16f2e09e2d4035bc19c2135d37a1d0":{
        "scriptId":"u7"},
      "d8cf724cbd934951a4d73f1b37501249":{
        "scriptId":"u8"}},
    "c6091bcf6d7c4ddab1cea2d107ab5a28":{
      "scriptId":"u9",
      "49ed5d571ebc47deb5cebc13c668cf56":{
        "scriptId":"u10"},
      "ee972d7e6bce42a7be40a4cec819d967":{
        "scriptId":"u11"},
      "5e1f04ce81654c5499486eefac74ea97":{
        "scriptId":"u12"},
      "0e0bddaa66bf446ea4e833d29316d0e3":{
        "scriptId":"u13"},
      "67a5021058454d6a839becccbdc39e43":{
        "scriptId":"u14"},
      "e9e38759bdf44e298e31bf83cca565a1":{
        "scriptId":"u15"},
      "0993f26346014d4bb26856d5e5d1db8d":{
        "scriptId":"u16"},
      "066c9b84b33240389b02efaced716c90":{
        "scriptId":"u17"},
      "760cf6f4d7e14daeacd018ba740d47bb":{
        "scriptId":"u18"},
      "e9766b0c194e4a29a9492e090163ebc9":{
        "scriptId":"u19"},
      "655d64d13b9e426fac601ad145b3f715":{
        "scriptId":"u20"},
      "7d931fa140ed4a7796b1f5c6b18b54a4":{
        "scriptId":"u21"},
      "af93c72b1694414587a00604ec54d3dd":{
        "scriptId":"u22"},
      "dffe95781d8b4c599a60053760cdfe99":{
        "scriptId":"u23"}},
    "7d20cd49ba9b455c89f135d7fcded0f8":{
      "scriptId":"u24"},
    "4064df8c326447efa8cd04ef7398d794":{
      "scriptId":"u25"},
    "07120830db1d4ebd948a20179d090b55":{
      "scriptId":"u26"},
    "0a7cbbab4eb64fa7b54bc2a3c7b6b810":{
      "scriptId":"u27"},
    "b363d1dcd52a4ac49b7582c56cd98152":{
      "scriptId":"u28",
      "edfc2f4ce39745e1bf776d40ceea8f59":{
        "scriptId":"u29"},
      "dcc53fc4119c489ba4c4387a5ce5891d":{
        "scriptId":"u30"},
      "d8ebf613679243f98e5e301233784516":{
        "scriptId":"u31"},
      "32ce2f1906d844189558c2f8a34fe123":{
        "scriptId":"u32"},
      "9affdfe40f654aa397ff2597ae37939b":{
        "scriptId":"u33"},
      "c1ff910c9c7348fba65de05303d26a24":{
        "scriptId":"u34"},
      "4fbc2d421ba1461dbe178b75808824c2":{
        "scriptId":"u35"},
      "fbd97f546dc54b009c185aa832f6466a":{
        "scriptId":"u36"},
      "d42d5d8bb2224092a300e745105c635d":{
        "scriptId":"u37"},
      "9f14d206462e48b9b40bab12bba2d31d":{
        "scriptId":"u38"},
      "d085552437cb4a2097533f961c404969":{
        "scriptId":"u39"},
      "6e7346c892eb49b68ad04ac33e1f7f1d":{
        "scriptId":"u40"},
      "86b2d89a36f844a38dd221378968b405":{
        "scriptId":"u41"},
      "28776cc25a17427b95cd43b610efee10":{
        "scriptId":"u42"},
      "7ea28152c03941299e4f169d094ebd59":{
        "scriptId":"u43"},
      "eacf152fe7754c0d9e032fb59580759a":{
        "scriptId":"u44"},
      "62e224545cd44e458675e6da3eaa401b":{
        "scriptId":"u45"},
      "5124ca61545c4c17b645962eaaca0a46":{
        "scriptId":"u46"},
      "b9245ee5ad6e4a31bd45ffd7a8579ee8":{
        "scriptId":"u47"},
      "3dc96932814c4e3bb92028225f4c9569":{
        "scriptId":"u48"},
      "cfe85946c4db4df29374b8393d5e1ade":{
        "scriptId":"u49"},
      "85b8630675134bc8b54e71921db21891":{
        "scriptId":"u50"},
      "0e15ad3662b14c369cdbac7ef4e96e5d":{
        "scriptId":"u51"},
      "cbd8267cf4044508b19c8b2ad0c72e9a":{
        "scriptId":"u52"},
      "39ea4dbb62c847e7816e41fa39a663f8":{
        "scriptId":"u53"},
      "1eae7af5be7d42278105e53ad6180c5c":{
        "scriptId":"u54"},
      "09df8f3ac6344f6782c35cdd4e133340":{
        "scriptId":"u55"},
      "d985f851eead4807900589566e27ebee":{
        "scriptId":"u56"},
      "8b2275de79fe4c27aba0ba15fa76752a":{
        "scriptId":"u57"},
      "4355a551ad1b4242a44a2412753f8dc6":{
        "scriptId":"u58"},
      "31dc927d10a74775bc9034e48c217a52":{
        "scriptId":"u59"},
      "26aa636b545c4947ae36bf3df06893fe":{
        "scriptId":"u60"},
      "0cac14fb90ee449bbfa615b84da9d38c":{
        "scriptId":"u61"},
      "ea4f935cf86b4c24a908c261333b946c":{
        "scriptId":"u62"},
      "3c79410579c2493eb7cbedd74d84920f":{
        "scriptId":"u63"},
      "7902d20f41f740a487e03bac900c7603":{
        "scriptId":"u64"},
      "e5d19c2b92ec4c9789da2cea3a74fe91":{
        "scriptId":"u65"},
      "a47e22c85df346839de86e05679962ba":{
        "scriptId":"u66"},
      "7d1c2fea52054efea49aef8961aef751":{
        "scriptId":"u67"},
      "4877d59f4c7b44c2bb6800ab1b3df9b2":{
        "scriptId":"u68"},
      "d49a78d46e25494a900cb6d5274956cb":{
        "scriptId":"u69"}},
    "b9d20eb24e5746e6bebe4b4a2d802c13":{
      "scriptId":"u70"},
    "de5c963c07b0460caa3fdfa34aa6ca79":{
      "scriptId":"u71"},
    "b98ce45a8a4844a382b9177227efbf9e":{
      "scriptId":"u72"},
    "06a1d00ca7214c428aaa8e07a66e6aa0":{
      "scriptId":"u73"},
    "34c44082f7024d9ebcffd2d33ba355e9":{
      "scriptId":"u74"},
    "08317e7d3a014b378a646d105c4d2e64":{
      "scriptId":"u75"},
    "7136eb51ec524896b72fdd7174e8a5a7":{
      "scriptId":"u76"},
    "f8aabe29714e436bb5dc5206517dd7ba":{
      "scriptId":"u77"},
    "861a7f79d54941b3947c4e0b544ee5c1":{
      "scriptId":"u78"},
    "f503b47a615549339d88e35f8563785a":{
      "scriptId":"u79"},
    "dfea0f93aeb94ac992deb19c22e2f0a3":{
      "scriptId":"u80"},
    "03392466eec9407fbf48b259743fbef1":{
      "scriptId":"u81"},
    "7758c7be9a304bce8f6406664bcb5769":{
      "scriptId":"u82"},
    "2921402605fa45318f0f5dcb220a5a7c":{
      "scriptId":"u83"},
    "1414f862ba6043e9a7a033f037e7e059":{
      "scriptId":"u84"},
    "748517f14f1942f5be9187d30784a68c":{
      "scriptId":"u85"},
    "102230b8c5c2432f8ab048a64d1e4a22":{
      "scriptId":"u86"},
    "efa2feafe585484cb7588e9a41855397":{
      "scriptId":"u87"},
    "5c7ae99e43b94a7d8cd5261fce002a84":{
      "scriptId":"u88"},
    "a5558cab979947beb39c2fb6231747cd":{
      "scriptId":"u89"},
    "d1b8e377b98a409d83650d1ee9aeeba4":{
      "scriptId":"u90"}}});